### ISSUE TITLE
Ycmd completion unavailable while parsing is in progress

### ISSUE THREAD

**Issue by r4nt** [abingham/emacs-ycmd#121]
@Valloric - somehow vim-ycm doesn't completely disable completions during parsing, right?

@abingham - can we make emacs-ycmd somehow still take the completion request? Otherwise company seems to fall back to clang-complete, which seems strange as default behavior...

**Comment by abingham** [comment]
It seems that this issue is resolving itself elsewhere, so I'm closing this until/unless anyone has any complaints.

**Comment by r4nt** [comment]
@abingham - btw, I think all the open issues I had are now resolved - thanks a lot for your work here, it's highly appreciated :)

**Comment by abingham** [comment]
Great, thanks! Honestly when left to my own devices I tend towards "works well enough for me", and emacs-ycmd wouldn't have near the level of polish it has without the kind of input you and others have given. So keep the ideas coming.
