### ISSUE TITLE
flycheck doesn't work for non-ycm languages after flycheck-ycmd-setup

### ISSUE THREAD

**Issue by r4nt** [abingham/emacs-ycmd#130]
When I use
(company-ycmd-setup)
(add-hook 'after-init-hook 'global-company-mode)
(add-hook 'prog-mode-hook 'ycmd-mode)
(flycheck-ycmd-setup)
(add-hook 'prog-mode-hook 'flycheck-mode)

I run into problems with flycheck on emacs lisp files:
When I open them, flycheck shows FlyC* in the command line (instead of FlyC:1/4), which apparently means "currently running" forever, and does not display any errors. The flycheck error list is empty.
I can get it to work by disabling ycmd (M-x ycmd-mode, then M-x flycheck-buffer, and it works fine).

**Comment by abingham** [comment]
I'm seeing the same thing, but I didn't recognize it as a problem until now. Are you only seeing it for elisp files? I seem to see it for all sorts of files.

This is likely a result of the fact that [we use flycheck in an unsupported way](https://github.com/flycheck/flycheck/issues/549). Flycheck expects clients to initiate checks (e.g. compilations) only when flycheck asks for them, but of course ycmd is requesting the parses on its own schedule and then attempting to prompt flycheck to look at the new results.

**Comment by r4nt** [comment]
I haven't tried with anything else. I mainly realized because somebody told me in a code review to use flycheck to see the errors of my way, and my reaction was "but I do...". Then I investigated and found that flycheck doesn't actually show me any errors.

**Comment by abingham** [comment]
I'm not entire sure what's going on here, but initial indications are that it's a problem with `flycheck`. I've [reported an issue](https://github.com/flycheck/flycheck/issues/564). Hopefully I'll know more soon.

**Comment by r4nt** [comment]
Thanks. Just for clarification (because the issue on flycheck you opened seems ambiguous): it's not only that the mode line is broken, I also don't get any flycheck errors on those files.

**Comment by abingham** [comment]
Right, I've added a note to that effect.

**Comment by abingham** [comment]
This might be fixed by https://github.com/flycheck/flycheck/issues/564. I'll test it out when the change makes its way into melpa.

**Comment by abingham** [comment]
Also, based on the config you showed, I wouldn't expect elisp flycheck to really work at all. You're putting every buffer with `prog-mode` into `ycmd-mode`. Then `flycheck-ycmd-setup` puts the `flycheck-ycmd` checker at the front of flycheck's list, meaning that that checker – and only that checker – will get used for every `prog-mode` buffer. The ycmd checker doesn't know anything about elisp and will effectively report that there are no errors.

I suppose I could change the `flycheck-ycmd` checker's predicate to check for both `ycmd-mode` and a supported major mode (of which we have a list in `ycmd.el`. Or we could require users to explicitly set up flycheck chaining. I'm not sure which is best, and I need to focus on some other stuff for a bit...hopefully I can give it some thought in the near future. Your best bet in the near term might be to me more explicit about which buffers you put into `ycmd-mode`.

(I hope that's all clear...)

**Comment by r4nt** [comment]
Thanks a lot for the info.
My main problem is that there are 2 things to ycm: auto-completion and syntax checking. I want ycm syntax checking (and thus flycheck integration) to be only active in a subset of buffers, but I want the ycm  auto-completion to be active by default in all buffers. I'm not sure there is currently a good way to do that (I assume I need ycmd-mode for auto-completion).

**Comment by abingham** [comment]
Probably the simplest solution is to maintain a list of modes for which flycheck-ycmd should do checking. If a buffer is in both `ycmd-mode` and a mode on that list, then we'll use flycheck-ycmd. Otherwise we'll pass checking on down the line. As long as you don't so something like putting `prog-mode` in that list, you should be able to accomplish what you're trying to do. I guess this approach is pretty symmetrical with what ycmd.el does, i.e. any buffer can be in `ycmd-mode` but we make sure not to pass anything to the server which isn't know to be supported by it.

**Comment by r4nt** [comment]
That sounds like a plan (@Valloric for a sanity check)

**Comment by ptrv** [comment]
Another simple solution is to make the variable `flycheck-checkers` local in buffers you want to add `flycheck-ycmd` to

for example if I only want `flycheck-ycmd` in `c++-mode`
```elisp
(add-hook 'c++-mode-hook
                  (lambda()
                     (add-hook 'ycmd-file-parse-result-hook 'flycheck-ycmd--cache-parse-results)
                     (make-local-variable 'flycheck-checkers)
                     (add-to-list 'flycheck-checkers 'ycmd)))
```

**Comment by Valloric** [comment]
Saw the bat signal from @r4nt; just wanted to mention that YCM used to use Syntastic (the Vim plugin equivalent to flycheck for emacs) for diagnostic display but moved away from it. YCM now does the diagnostic UI itself. The reason for the switch was an impendance mismatch between the Syntastic model and how YCM worked; putting a square peg into a round hole caused perf issues, bugs and missing features etc. You seem to be encountering a similar situation.

By all means, rely on flycheck if at all possible. But keep in mind that if you really want to ensure high quality error reporting you may end up having to implement the error display UI yourself. YCM switched to its own setup while being almost entirely backwards compatible with the old Syntastic setup (even falling back to interpreting Syntastic conf options). I'd estimate 99.999% of users never knew something changed.

But again, stick to flycheck if you can.

**Comment by lunaryorn** [comment]
@abingham Can't you check whether ycmd actually supports the current buffer, either in `ycmd-mode` itself, or in the `:predicate` of the syntax checker at least?

Ideally, you'd disable `ycmd-mode` automatically if it doesn't support the current buffer.

**Comment by abingham** [comment]
@Valloric Thanks for the info. I don't think there's really too much of a mismatch in this case. We just need a mechanism to more cleanly distinguish between files which use ycmd for completion and error reporting, and those which just use it for completion. I don't *think* there's a case where we'd just use it for error reporting, but I'm sure someone will eventually tell me if I'm wrong. And flycheck is so good that I'd hate to have to replicate it!

**Comment by abingham** [comment]
@lunaryorn Yes, using `:predicate` to filter out modes unsupported by ycmd is one thing we almost certainly should do. As you say, we can make it automatic and free, and there's no downside to doing it.

At the same time, I think users will also want to explicitly filter some modes from `flycheck-ycmd` e.g. because they'd prefer some other "downstream" checker to handle that mode.

**Comment by lunaryorn** [comment]
@abingham For this purpose Flycheck provides `flycheck-disabled-checkers`.

**Comment by abingham** [comment]
@lunaryorn Ah yes, I use this myself but hadn't noticed that it's buffer-local. I'll add a note to the readme about disabling ycmd for some modes by updating that list in the appropriate hook.

**Comment by abingham** [comment]
@r4nt The problem you initially reported seems to be fixed in recent version of `flycheck`. Can you verify this?

**Comment by abingham** [comment]
Also, as of 13c3511b9d3da938285b1405bad82128800e6e2f `flycheck-ycmd` won't try to check modes that aren't supported by ycmd (e.g. emacs-lisp.)

**Comment by r4nt** [comment]
This now definitely works for emacs-lisp. I'm slightly surprised that ycmd supports that many languages (doesn't show me perl errors, but perhaps I misconfigured?)

**Comment by abingham** [comment]
I don't remember exactly where I got that list of languages, but I assume it's from the ycmd source somewhere. 

Regarding perl: are you perhaps using cperl-mode? If so, then currently we'd ignore your file. I really should make the mode->type mapping extensible.

**Comment by Valloric** [comment]
The only languages for which ycmd provides diagnostic errors are the C-family (C/C++/Objective-C/Objective-C++), Python and C#, AFAIR.

**Comment by abingham** [comment]
OK, thanks, it sounds like I misinterpreted something and that I need to limit ycmd error reporting to just those languages
