### ISSUE TITLE
Make the file-type-map extensible

### ISSUE THREAD

**Issue by abingham** [abingham/emacs-ycmd#132]
Currently we hard code the major-mode to ycmd-type mapping in `ycmd--file-type-map`. This may be problematic for cases where people use "alternative" major modes like `cperl-mode` instead of `perl-mode` for perl.

**Comment by abingham** [comment]
Fixed in fef219f535f1eec03a160eafcc5200dd5a8e00c6 with a new `defcustom`.

**Comment by abingham** [comment]
@r4nt I added `cperl-mode` to the file-type-map, so perhaps I've already addressed your perl problems. But this change should give you the ability to map arbitrary modes to ycmd file type strings.

**Comment by r4nt** [comment]
So, what I'm still unsure about - aren't *all* major modes supported for (non-semantic) identifier completion?

**Comment by abingham** [comment]
They should be, I think. At least that's the intent. Anything mode that's not in the type-map gets passed to ycmd as "generic". The map just exists so that we can give ycmd information about file types that it might be able to do something extra with.
