### ISSUE TITLE
Limit flychecking to just a few languages

### ISSUE THREAD

**Issue by abingham** [abingham/emacs-ycmd#134]
From valloric: "The only languages for which ycmd provides diagnostic errors are the C-family (C/C++/Objective-C/Objective-C++), Python and C#, AFAIR." So we need to limit the application of flycheck to just these languages. These are the languages that get semantic completion.

All other languages (and buffers of any sort, I suppose) get identifier-based completion.

**Comment by abingham** [comment]
@valloric I plan to expect diagnostics for only the file types "c", "cpp", "objc", "objcpp", "cs", and "python".  Does that sound right? This all looks pretty straightforward, but I just wanted to double check.

**Comment by Valloric** [comment]
> @valloric I plan to expect diagnostics for only the file types "c", "cpp", "objc", "objcpp", "cs", and "python". Does that sound right? This all looks pretty straightforward, but I just wanted to double check.

:+1: 

> Also, I suppose this list of file types may change/grow in the future. It might be a good idea if ycmd had a function for reporting the file types with semantic support. I could query that when I start the server instead of hard-coding a list.

Agreed, open an issue on ycmd's tracker.

**Comment by Valloric** [comment]
I just checked and it seems I lied; ycmd doesn't provide diagnostics for Python. It's only C-family and C#.

**Comment by abingham** [comment]
Fixed in c50a5301398d93c15c9f79b07c79b6a9b88ecb69
