### ISSUE TITLE
Get tests working again

### ISSUE THREAD

**Issue by abingham** [abingham/emacs-ycmd#135]
I've apparently broken the tests somehow. Get them working again.

**Comment by abingham** [comment]
One immediate problem is that we're not copying the .ycmd-extra-conf.py into the directory with the source, so ycmd is not providing any completions.

**Comment by abingham** [comment]
Perhaps we should not use C++ and/or semantic completions in general. We really just want to test the plumbing, so it's a lot of extra work to set up the compilation, etc. We can just use something with identifier completion.

**Comment by ptrv** [comment]
@abingham I started to improve our testsuite on branch [improve-testsuite](https://github.com/abingham/emacs-ycmd/tree/improve-testsuite)

I noticed that `ycmd` had problems reading my global config when the file to parse was a temp file, so I implemented the tests to directly use the provided test file. Also I think we need to use a `ycm_extra_conf.py` file for running the tests.

The `goto-declaration` test was broken and is fixed now.

One thing I noticed that I only can run the tests when I run them in an Emacs session. I tried to run them from a Makefile with emacs in batch mode but somehow the server cannot be started and I get a `"Server timeout"` error. Do you have an idea what the problem could be?

**Comment by abingham** [comment]
Your changes look good, and I'd be happy to merge them in immediately. I really like having the "resource" directory.

I don't know why things don't work in batch mode, but I'll see about trying it out this evening. I remember having trouble in the past with stdout buffering; Python wasn't flushing its buffers so we never saw the port number, and it appeared like the server wasn't getting started. You might see if the ycmd server is getting started at all, e.g. with `ps` or `top`.

**Comment by ptrv** [comment]
Yes, would be great if you could test the branch. I committed a makefile, cask file and a runner script. You need to install [Cask](http://cask.github.io/) for the makefile to work. But it;s really nice because it handles the dependencies for the batch-mode

**Comment by abingham** [comment]
I think the basic problem with running the tests in batch is that batch
mode skips initialization files. As such, the user's config never gets a
chance to set e.g. ycmd-server-command. When I inserted a line to print the
proc-output from the server command, it just repeatedly printed messages
saying it couldn't find our dummy default path to ycmd. I'm not sure if
there is a way to run in batch mode and load init files.

**Comment by ptrv** [comment]
ok, then we have to set up all needed variables in the runner script. I'll have a look into it.

**Comment by ptrv** [comment]
@abingham You were absolutely right with the variables.

I was able to run the test with the `Makefile` by binding `ycmd-server-command` locally.

**Comment by ptrv** [comment]
See #238
