### ISSUE TITLE
Flycheck seems to think it's processing (FlyC*) when ycmd is enabled

### ISSUE THREAD

**Issue by r4nt** [abingham/emacs-ycmd#139]
When I produce errors in my C++, I'd expect the status line to say FlyC:42/0 giving me the number of errors. Instead I see FlyC*; according to a different issue I think this says that flycheck still is in the state where it thinks it's processing?

**Comment by r4nt** [comment]
Ignore me, I had an old version of flycheck via a different packaging mechanism ...

**Comment by abingham** [comment]
*whew*. I was about to really confused.
