### ISSUE TITLE
column_num not computed correctly when line contains tabs

### ISSUE THREAD

**Issue by ekfriis** [abingham/emacs-ycmd#170]
Hello,

I'm working on implementing support for Go completion in ycmd (Valloric/ycmd/pull/106). The completion tool [1] takes a byte offset instead of a line and column, which I compute from the contents, line and column.

emacs-ycmd is reporting the column using (current-column), which is the visual column, with `\t` being `tab-width` instead of 1. ycmd expects the column to be a byte offset. 

Please let me know if there is anything I can do to help or if more specific reproduction instructions are needed.

[1] https://github.com/nsf/gocode
[2] https://github.com/abingham/emacs-ycmd/blob/master/ycmd.el#L886

**Comment by abingham** [comment]
Thanks for pointing that out. It looks like we've been violating the ycmd protocol up to now wrt column offsets! If you don't mind, give the (column-in-bytes)[https://github.com/abingham/emacs-ycmd/tree/column-in-bytes] branch a try. It should be reporting columns in bytes.

I've done some spot-testing with this branch and it seems to work correctly on C++, Python, etc. But all of the code I've got handy uses spaces, not tabs. I also tested the column-in-bytes calculation a bit, but I imagine you're in a better position to test the whole stack than I am.

**Comment by abingham** [comment]
This should be fixed by 19bac74a508073d55952c4590b0e159a9d1fbb8a in master. Give it a shot. If it fixes the problem, then please close this issue. If not, let me know if it's still broken in the same way.

**Comment by ekfriis** [comment]
Sorry for such a delayed response - the fix looks perfect. I have an non-straightforwad emacs setup at work and am terrible at emacs, so I am having some trouble overriding the installed version to test. However, I'm in touch with some smarter people so I will be able to test it soon.

Thanks a lot for the fast fix!

**Comment by abingham** [comment]
Excellent, I hope it works for you.

If you want to try out the new code, one simple way is:
1. Open the fixed version of `ycmd.el` in emacs.
2. In that buffer, run `M-x eval-buffer`. This should "replace" the installed version for your current session.

Then you can restart emacs (or eval the installed) version to restore the installed version. At least, I *think* that ought to work.

Or you can just wait for the "smarter" people ;)

**Comment by ptrv** [comment]
@abingham @ekfriis a bit offtopic, but I am working on properly supporting `go` completion in `company-ycmd`. https://github.com/ptrv/emacs-ycmd/tree/gocode-support

Needed to refactor a bit to make stuff like getting annotation or meta more generic. Also the `ycmd` server reports completion for different languages differently and we generate annotation or meta from different tags. Basically we have different `construct-candidates` for different languages.

Here you can see a diff: https://github.com/abingham/emacs-ycmd/compare/master...ptrv:gocode-support

**Comment by abingham** [comment]
It's a bit frustrating that `ycmd` gives different information for different languages. Do you know if this is intentional? If it is then I assume there's a good reason, but I had hoped that `ycmd` would give a consistent abstraction over all supported languages.

**Comment by ptrv** [comment]
@abingham I mean, the semantics are different over different languages and we need to display them differently in annotations and meta. Also the completion backends like `clang`, `jedi` and `gocode` are reporting different things

**Comment by abingham** [comment]
Ah, so it's not as bad as I had thought.

**Comment by ptrv** [comment]
@abingham No. And also, usually you use different company backends for different languages and purposes. `ycmd` serves completion for a variety of languages and we use one company backend.
