### ISSUE TITLE
Trigger semantic completion?

### ISSUE THREAD

**Issue by naseer** [abingham/emacs-ycmd#183]
Right now `ycmd-toggle-force-semantic-completion ` switches the mode for everything. Is there a way to get company to semantic complete only when required, maybe when using a different keyboard shortcut (say <kbd>Shift</kbd>+<kbd>TAB</kbd>)

This would make the behaviour similar to vim.

**Comment by ptrv** [comment]
You could write a function like:

```lisp
(defunct company-ycmd-semantic-complete ()
  (let ((company-ycmd-force-semantic-completion t))
    (company-complete)))
```

and bind it to a to key.

**Comment by naseer** [comment]
@ptrv - thanks for the suggestion, will try it out

**Comment by naseer** [comment]
@ptrv worked like a charm ! :+1:

**Comment by naseer** [comment]
(only change needed was to add (interactive) so that global-set-key works

**Comment by ptrv** [comment]
@naseer yes, I forgot to add `(interactive)`, sorry. Glad that it works for you.
