### ISSUE TITLE
Flycheck-ycmd doesn't support C++11

### ISSUE THREAD

**Issue by andyque** [abingham/emacs-ycmd#190]
When enable Flycheck-ycmd in my c++11 project, it gives me many wrong errors:

Such as:  "nullptr is not compatible with c++98"

How can I configure ycmd to support c++11?

Thanks.

**Comment by andyque** [comment]
@Valloric Could you help me to resolve it?  Thanks :)

**Comment by ptrv** [comment]
Did you set `-std=c++11` flag in ycm_extra_conf.py?

**Comment by abingham** [comment]
@ptrv is almost certainly right: make sure you've set the appropriate build flags in ycmd_extra_conf.py. That's the only way ycmd knows how to correctly compile your code.

**Comment by andyque** [comment]
Thanks, @ptrv @abingham 
I removed "-Wc++98-compat" flag from ycmd_extra_conf.py and the error disappeared.
