### ISSUE TITLE
Redundant braket when complete function name with no parameters

### ISSUE THREAD

**Issue by zhuzhongshu** [abingham/emacs-ycmd#195]
I find when I try to complete a function name with no parameters, a rudundant braket will appended  with the function name, so there are two brakets in total after completion. For example, we can try the function `std::clock()` as can be seen in the next figure:
![160-504](https://cloud.githubusercontent.com/assets/8487906/7851777/4d8db110-0527-11e5-870d-0c262e8d2abc.png)

After completion, we get `std::clock()()`.

**Comment by ptrv** [comment]
This has been fixed a while a go in upstream `ycmd` server. Are your `emacs-ycmd` and `ycmd` up to date?

**Comment by zhuzhongshu** [comment]
Sorry, my ycmd server is an old version. I will update it. Thanks!

**Comment by ptrv** [comment]
Please close ticket if the `ycmd` server update fixes your issue.
