### ISSUE TITLE
Bug when starting emacs with multiple files

### ISSUE THREAD

**Issue by abingham** [abingham/emacs-ycmd#197]
It looks like we have a bug in ycmd when we start emacs with multiple files. If I start emacs like this:
```
emacs some_file.cpp another_file.cpp
```
then I get a server timeout in `*messages*`:
```
progn: Server timeout.
```
This might have to do with multiple calls to ycmd-open, but it's not clear right now.

**Comment by abingham** [comment]
@ptrv Do you see anything like this? I was trying out your latest patch when I came across it.

**Comment by ptrv** [comment]
@abingham I haven't seen this issue so far. But I never started emacs like you mentioned above.

**Comment by abingham** [comment]
I can no longer replicate this error, so I'm not sure if it's gone or just hidden. I'll close this for now and look into it again if comes back...
