### ISSUE TITLE
ycmd-close: Invalid function: ycmd--kill-timer  on the latest MELPA

### ISSUE THREAD

**Issue by andyque** [abingham/emacs-ycmd#199]
This issue is critical, my Emacs even can't close now if I have enabled ycmd. 
Please fix it, thanks.

**Comment by abingham** [comment]
Are there any suspicious looking messages  in the message buffer? And what version of emacs are you using?

**Comment by abingham** [comment]
I ask because I don't see how that could be undefined...it's a macro that we just merged in, so it should be there.

**Comment by abingham** [comment]
Also could you check to see if ycmd--kill-timer is actually defined in the source that melpa is giving you?

**Comment by ptrv** [comment]
It sounds like `ycmd.el` was somehow evaluated partially after an update or does this happen also after restarting Emacs?

I had the same kind of error already sometimes when I was switching branches while development and I evaluated only parts of the file while other functions and definitions were from a different commit.

**Comment by andyque** [comment]
@abingham  @ptrv 
I deleted the ycmd.elc and call `byte-compile-file` to re-compile the ycmd.el file. Then the problem gone.
I do switch branches when using Emacs. Maybe that's the problem.

Thanks.

**Comment by ptrv** [comment]
@andyque Great that you could solve the problem.

I meant switching branches of an Emacs package repository (i.e. `ycmd.el`) while developing it.

**Comment by naseer** [comment]
I had the same problem in spacemacs, deleting ycmd.elc solved the problem, thanks!

**Comment by andyque** [comment]
@naseer  I'm also using spacemacs, maybe it's bug in spacemacs.

**Comment by abingham** [comment]
Interestingly, I've also been trying out spacemacs recently, and I ran into this exact problem yesterday. I agree with @andyque that this really seems like a spacemacs issue, or perhaps a melpa/package.el problem. Has anyone filed an issue with them?

**Comment by ptrv** [comment]
The error was due to the fact that the macro was defined further down in the code then the first usage in `ycmd-close`. Moving it before first usage fixes the issue.

I could repro the issue with byte-compiling `ycmd.el` and restarting emacs and loading a c++ file. I don't know whether the issue came up when loading `ycmd` lazily with `eval-after-load` or etc.

**Comment by ptrv** [comment]
From the info `(elisp) Compiling Macros`:
> In order for compilation of macro calls to work, the macros must already be defined in Lisp when the calls to them are compiled.
