### ISSUE TITLE
ycmd server (spacemacs)

### ISSUE THREAD

**Issue by jvillasante** [abingham/emacs-ycmd#205]
I'm using ycmd on spacemacs, this is my configuration:

dotspacemacs-configuration-layers '(ycmd)

(add-hook 'after-init-hook #'global-ycmd-mode)
(set-variable 'ycmd-server-command '("python" "~/bin/ycmd/ycmd"))

ycmd is installed correctly on ~/bin/ycmd/ycmd and inside that dir __main__.py exists!

And this is the error I'm getting on the *ycmd-server*:
/usr/bin/python: can't open file '~/bin/ycmd/ycmd': [Errno 2] No such file or directory
Process ycmd-server exited abnormally with code 2

I've tried setting ycmd-server-command with relative paths, non relative paths, with the path all the way to __main__.py but always getting the same error.

**Comment by ptrv** [comment]
It looks like `~` doesn't get expanded. Could you please try to use the absolute path without tilde?

**Comment by ptrv** [comment]
@jvillasante Did the last comment solve your issue?

**Comment by jvillasante** [comment]
Not really, `~` was got expanded normally. I reinstalled all my packages and it started working again.

**Comment by ptrv** [comment]
Ok, then I close the issue.
