### ISSUE TITLE
Show compilation errors in debug-info

### ISSUE THREAD

**Issue by jamescasbon** [abingham/emacs-ycmd#206]
I am getting `RuntimeError: No completions found; errors in the file?`

How can I see the errors?

The server log only shows the python traceback.  The debug info only shows the compile flags.

**Comment by abingham** [comment]
You're seeing this output in the `*ycmd-server*` buffer, right? You might try adding "--log debug" to the ycmd command line (i.e. via `ycmd-server-command`). Perhaps that will give you more info.

@valloric Any suggestions as to how to get more info in this situation?

**Comment by Valloric** [comment]
This error means that ycmd was unable to get any completions out of libclang for that location in the file. Which means that libclang couldn't compile the file. Which means there's probably an unrecoverable compilation error somewhere before that location in the file.

First step is to resolve any diagnostic errors that ycmd is showing, if any.

Second, a solid way to test this out is to take the same flags that ycmd is using for the file (which you can get from ycmd debug info; don't know how emacs-ycmd exposes it) and give that to clang-the-binary. It should spit something out.

**Comment by jamescasbon** [comment]
OK, I managed to get this to work by switching to a clang completion database. 

I still think this would be nice to have, but you can reopen if you want to support that.
