### ISSUE TITLE
Company-ycmd not completing in certain cases

### ISSUE THREAD

**Issue by sollidsnake** [abingham/emacs-ycmd#214]
I installed and configured `emacs-ycmd` and it works, but it doesn't seem to complete functions. Example:
```
#include <stdio.h>
#include <iostream>

int main() {
    std:: // case 1
    pri // case 2

    return 0;
}
```
If I ask to complete in case 1, it completes correctly, but in case 2, I don't get any candidate when I invoke the command `company-ycmd`. With the line `using namespace std` also doesn't work.

I tried a lot of `.ycm_extra_conf.py` tweaking, but no use.

**Comment by ptrv** [comment]
I tried your example, and it works for me. Can you post your `ycmd_extra_conf.py`?

**Comment by ptrv** [comment]
Wait, I think I found out why it doesn't work for you? Could you try run `ycmd-toggle-force-semantic-completion`? It should work then.

The problem is, when parsing the line with `pri`, we get only `pri` without any trigger for semantic completion like `.`, `->` or `::`  as completion prefix and when we send it to `ycmd`, the server tries to send back identifier completion. If you turn on `force-semantic-completion` then the server will send completion for `printf`.

**Comment by sollidsnake** [comment]
That was it. After setting that variable it works. Maybe it should enabled by default? 
Thanks!

**Comment by abingham** [comment]
I think that's disabled by default for performance reasons.

**Comment by abingham** [comment]
Just for completeness, [here is the issue where we discuss the slowness of always using semantic completion](https://github.com/abingham/emacs-ycmd/issues/169). Search for the first occurrence of "unhappy".

**Comment by sollidsnake** [comment]
I see. And I agree it's slow and should not be triggered automatically. But one would expect to have completion without depending on triggerers when explicitly invoking the command.

**Comment by ptrv** [comment]
@sollidsnake I agree. I have this in my config to trigger semantic completion when I invoke explicitly:

```elisp
(defun company-ycmd-complete ()
  (interactive)
  (let ((ycmd-force-semantic-completion t))
     (company-complete)))
(define-key ycmd-mode-map [remap complete-symbol] #'company-ycmd-complete)
``` 
The function `company-ycmd-complete` is used when I invoke company-complete with a key command and it triggers semantic completion.

**Comment by abingham** [comment]
I guess if we could distinguish between explicit completion requests (i.e. a user specifically asking for completion via a key combination or something) vs. on-the-fly completion (i.e. completion being done by company as the user types), then we could force semantic completion in the explicit version. In this case the performance penalty wouldn't be interrupting typing flow.

I don't really have time to look into this, but it might give us the best of both worlds.
