### ISSUE TITLE
Go back to previous location?

### ISSUE THREAD

**Issue by dongz9** [abingham/emacs-ycmd#227]
Hi,

Is there anyway to go back to my previous location after jumping to the definition?

Thanks!

-- Dong

**Comment by ptrv** [comment]
You can get back to the previous loication after a `ycmd-goto` command with `pop-tag-mark` which is bound to `M-,` in Emacs 25 and I think `M-*` in Emacs 24.

**Comment by ptrv** [comment]
@dongz9 Is your question answered? Can this issue be closed?

**Comment by dongz9** [comment]
@ptrv Yes, I'm closing the issue.
