### ISSUE TITLE
Cannot connect to ycmd server

### ISSUE THREAD

**Issue by mssun** [abingham/emacs-ycmd#228]
When I open `ycmd-mode`, there is an error `REQUEST [error] Error (error) while connecting to http://127.0.0.1:41211/event_notification.`. When trying to type something, ycmd said that `Ycmd completion unavailable while parsing is in progress.`. I don't know how long does it take to process the completion, but I waited for a long time and still couldn't work.

I try to debug the problem. I found that the ycmd server process was already started. How do I know if my ycmd client can successfully communicate with server?

**Comment by abingham** [comment]
If you run `M-x ycmd-open`, does it start to work?

**Comment by mssun** [comment]
No, still got the same error.

**Comment by abingham** [comment]
Are you sure you've got a recent version of ycmd? We can run into protocol mismatches if the client and server versions are substantially different.

**Comment by mssun** [comment]
Thank you for your quick reply. Yes, I cloned from ycmd GitHub and compiled from the latest master version. And the emacs-ycmd downloaded from elpa is `ycmd-20151028.634`. I am using Arch Linux and Spacemacs ycmd layer. I am trying to use a clean Emacs config to debug this issue. I am not sure if this is caused by Spacemacs configuration.

**Comment by abingham** [comment]
There have definitely been reports of problems that only seem to happen with spacemacs. Can you possibly try this with a non-spacemacs version of emacs?

**Comment by abingham** [comment]
Can you attach your .spacemacs file and/or any custom layers (or a git repo with it)? That way I can try to duplicate what you're seeing.

**Comment by abingham** [comment]
Also, you might set `ycmd--log-enabled` and check the `*ycmd-content-log*` buffer for suspicious messages as well. This will be a log of HTTP traffic.

**Comment by mssun** [comment]
Ok, I will try then later. BTW, I am using it behind proxy. Will it affect
the communication?

**Comment by abingham** [comment]
I don't think a proxy should be a problem. All of the communication is to
127.0.0.1.

**Comment by mssun** [comment]
`ycmd-server` buffer:

```
2015-11-06 09:41:03,278 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
serving on http://127.0.0.1:37708
2015-11-06 09:41:04,160 - INFO - Received event notification
2015-11-06 09:41:04,160 - DEBUG - Event name: FileReadyToParse
2015-11-06 09:41:04,160 - INFO - Adding buffer identifiers for file: /home/mssun/test/test.cpp
Traceback (most recent call last):
  File "/home/mssun/program/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/home/mssun/program/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/home/mssun/program/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper
    return callback( *args, **kwargs )
  File "/home/mssun/program/ycmd/ycmd/../ycmd/hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "/home/mssun/program/ycmd/ycmd/../ycmd/handlers.py", line 71, in EventNotification
    event_handler )( request_data )
  File "/home/mssun/program/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 368, in OnFileReadyToParse
    raise ValueError( NO_COMPILE_FLAGS_MESSAGE )
ValueError: Still no compile flags, no completions yet.
2015-11-06 09:41:33,293 - INFO - Received health request
2015-11-06 09:42:03,293 - INFO - Received health request
```

`ycmd-content-log` buffer:
```
HTTP REQUEST CONTENT

"{\"event_name\":\"FileReadyToParse\",\"file_data\":{\"\\/home\\/mssun\\/test\\/test.cpp\":{\"contents\":\"#include <stdint.h>\\n#include <stdio.h>\\n#include <string.h>\\n#include <fcntl.h>\\n#include <sys\\/stat.h>\\n#include <unistd.h>\\n#include <stdlib.h>\\n#include <random>\\n#include <unordered_set>\\n#include <unordered_map>\\n\\n#include <vector>\\n\\n\\/* struct k_raw_args { *\\/\\n\\/*     int argc; *\\/\\n\\/*     char argv[2][10]; *\\/\\n\\/*     int envp[2]; *\\/\\n\\/*     int auxv[2]; *\\/\\n\\/* }; *\\/\\n\\/* int main() { *\\/\\n\\/*     struct k_raw_args raw_args; *\\/\\n\\/*     raw_args.argc = 1; *\\/\\n\\/*     memset(raw_args.argv[0], 0, 10); *\\/\\n\\/*     memset(raw_args.argv[1], 0, 10); *\\/\\n\\/*     raw_args.envp[0] = 0; *\\/\\n\\/*     raw_args.envp[1] = 0; *\\/\\n\\/*     raw_args.auxv[0] = 1; *\\/\\n\\/*     raw_args.auxv[1] = 2; *\\/\\n\\/*     int argc; *\\/\\n\\/*     char** argv; *\\/\\n\\/*     char** envp; *\\/\\n\\/*     int* auxv; *\\/\\n\\n\\/*     uintptr_t* args = reinterpret_cast<uintptr_t*>(&raw_args); *\\/\\n\\/*     argc = static_cast<int>(*args); *\\/\\n\\/*     printf(\\\"argc: %d\\\\n\\\", argc); *\\/\\n\\/*     argv = reinterpret_cast<char**>(args + 1); *\\/\\n\\/*     printf(\\\"argv: %s\\\\n\\\", argv[0]); *\\/\\n\\/*     envp = argv + argc + 1; *\\/\\n\\/*     printf(\\\"envp: %x\\\\n\\\", envp[0]); *\\/\\n\\n\\/*     \\/\\/ Skip over all environment variable definitions to find aux vector. *\\/\\n\\/*     \\/\\/ The end of the environment block is marked by two NULL pointers. *\\/\\n\\/*     char** p = envp; *\\/\\n\\/*     while (*p != NULL) { *\\/\\n\\/*         ++p; *\\/\\n\\/*     } *\\/\\n\\/*     ++p; \\/\\/ Skip second NULL; *\\/\\n\\n\\/*     auxv = reinterpret_cast<int*>(p); *\\/\\n\\/*     printf(\\\"%x\\\\n\\\", *auxv); *\\/\\n\\/*     return 0; *\\/\\n\\/* } *\\/\\n\\n\\/\\/ #define BUFFER_SIZE 10240\\n\\/\\/ int main() {\\n\\/\\/     unsigned long start, end;\\n\\/\\/     unsigned long flags = 0;\\n\\/\\/     char flag_char[4] = {0};\\n\\/\\/     unsigned long long pgoff = 0;\\n\\/\\/     unsigned int major_dev, minor_dev;\\n\\/\\/     unsigned long ino = 0;\\n\\/\\/     char pathname[256] = {0};\\n\\/\\/     char buffer[BUFFER_SIZE] = {0};\\n\\/\\/     char *token;\\n\\/\\/     strcat(pathname, \\\"\\/proc\\/self\\/maps\\\");\\n\\/\\/     int fd = open(pathname, O_RDONLY);\\n\\/\\/     int n = read(fd, buffer, BUFFER_SIZE);\\n\\/\\/     char delim[] = \\\"\\\\n\\\";\\n\\/\\/     for (token = strtok(buffer, delim); token; token = strtok(NULL, delim)) {\\n\\/\\/         int ret = sscanf(token, \\\"%16lx-%16lx %s %16llx %02x:%02x %lu%s\\\",\\n\\/\\/         &start, &end, flag_char, &pgoff, &major_dev, &minor_dev, &ino,\\n\\/\\/         pathname);\\n\\/\\/         printf(\\\"%s\\\\n\\\", pathname);\\n\\/\\/     }\\n\\/\\/     return 0;\\n\\/\\/ }\\n\\ntypedef struct interval_node {\\n  int value;\\n  int less;\\n  int greater;\\n} IntervalNode;\\n\\ntypedef struct interval {\\n  int min;\\n  int max;\\n} Interval;\\n\\nint search(IntervalNode *interval_nodes, float key, int imin, int imax) {\\n  int imid = 0;\\n  while (imax >= imin) {\\n    imid = (imin + imax) >> 1;\\n    if (interval_nodes[imid].value == key) {\\n      return imid;\\n    } else if (interval_nodes[imid].value < key) {\\n      imin = imid + 1;\\n    } else {\\n      imax = imid - 1;\\n    }\\n  }\\n\\n  if (key < imid) {\\n    return interval_nodes[imid].less;\\n  } else {\\n    return interval_nodes[imid].greater;\\n  }\\n  return -1;\\n}\\n\\nint main(int argc, char **args) {\\n  int i = 0;\\n  int j = 0;\\n\\n  if (argc < 2)\\n    return 0;\\n  Interval intervals[5];\\n  intervals[0].min = 0;\\n  intervals[0].max = 1;\\n\\n  intervals[1].min = 1;\\n  intervals[1].max = 2;\\n\\n  intervals[2].min = 3;\\n  intervals[2].max = 4;\\n\\n  intervals[3].min = 4;\\n  intervals[3].max = 5;\\n\\n  intervals[4].min = 5;\\n  intervals[4].max = 6;\\n\\n  IntervalNode interval_nodes[7];\\n  for (i = 0; i < 7; i++) {\\n    interval_nodes[i].value = 0;\\n    interval_nodes[i].less = -1;\\n    interval_nodes[i].greater = -1;\\n  }\\n\\n  int last = 0;\\n  for (j = 0, i = 0; i < 5; i++) {\\n    if (last == intervals[i].min)\\n      continue;\\n    interval_nodes[j++].value = intervals[i].min;\\n    interval_nodes[j].greater = i;\\n    interval_nodes[j++].value = intervals[i].max;\\n    last = intervals[i].max;\\n  }\\n\\n  for (i=0;i<7;i++) {\\n    printf(\\\"interval_nodes: %d\\\\n\\\", interval_nodes[i].value);\\n  }\\n\\n  interval_nodes[0].value = 0;\\n  interval_nodes[0].less = -1;\\n  interval_nodes[0].greater = 0;\\n\\n  interval_nodes[1].value = 1;\\n  interval_nodes[1].less = 0;\\n  interval_nodes[1].greater = 1;\\n\\n  interval_nodes[2].value = 2;\\n  interval_nodes[2].less = 1;\\n  interval_nodes[2].greater = -1;\\n\\n  interval_nodes[3].value = 3;\\n  interval_nodes[3].less = -1;\\n  interval_nodes[3].greater = 2;\\n\\n  interval_nodes[4].value = 4;\\n  interval_nodes[4].less = 2;\\n  interval_nodes[4].greater = 3;\\n\\n  interval_nodes[5].value = 5;\\n  interval_nodes[5].less = 3;\\n  interval_nodes[5].greater = 4;\\n\\n  interval_nodes[6].value = 6;\\n  interval_nodes[6].less = 4;\\n  interval_nodes[6].greater = -1;\\n\\n  int res = search(interval_nodes, atof(args[1]), 0, 6);\\n  printf(\\\"res: %d\\\\n\\\", res);\\n  return 0;\\n}\\n\\nvoid patrickpatrickpatrick(int test) {}\\n\\nint test() {\\n}\\n\",\"filetypes\":[\"cpp\"]}},\"filepath\":\"\\/home\\/mssun\\/test\\/test.cpp\",\"line_num\":1,\"column_num\":1}"
HTTP RESPONSE CONTENT

((message . "Still no compile flags, no completions yet.")
 (traceback . "Traceback (most recent call last):\n  File \"/home/mssun/program/ycmd/third_party/bottle/bottle.py\", line 861, in _handle\n    return route.call(**args)\n  File \"/home/mssun/program/ycmd/third_party/bottle/bottle.py\", line 1734, in wrapper\n    rv = callback(*a, **ka)\n  File \"/home/mssun/program/ycmd/ycmd/../ycmd/watchdog_plugin.py\", line 100, in wrapper\n    return callback( *args, **kwargs )\n  File \"/home/mssun/program/ycmd/ycmd/../ycmd/hmac_plugin.py\", line 62, in wrapper\n    body = callback( *args, **kwargs )\n  File \"/home/mssun/program/ycmd/ycmd/../ycmd/handlers.py\", line 71, in EventNotification\n    event_handler )( request_data )\n  File \"/home/mssun/program/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py\", line 368, in OnFileReadyToParse\n    raise ValueError( NO_COMPILE_FLAGS_MESSAGE )\nValueError: Still no compile flags, no completions yet.\n")
 (exception
  (TYPE . "ValueError")))

HTTP REQUEST CONTENT

"null"
HTTP RESPONSE CONTENT

"true"
```

**Comment by mssun** [comment]
I figure out what goes wrong. If there is a blank `.clang_complete` file in the project, this issue will appear. And when I switch to a project which has a `.clang_complete` with some content (e.g., -std=c++11), ycmd works as normal.

**Comment by abingham** [comment]
Interesting. I'll try to replicate this later today and see if I can help. It would be nice if emacs-ycmd provided some better feedback than it is.

**Comment by abingham** [comment]
I've played around with this is a bit, and I can't find any correlation between an empty `.clang_complete` and completion errors. Have you checked with the clang project to see if they know anything about this?

**Comment by mssun** [comment]
I haven't reported to clang project. Did you successfully reproduce my issue?

**Comment by abingham** [comment]
Sorry, I should have been more clear. I am not able to replicate the problems you're seeing, even with spacemacs.

**Comment by mssun** [comment]
Here is my Spacemacs configuration: https://github.com/mssun/dotfiles/blob/master/.spacemacs

I can replicate the problems every time by using this setup:

```
mkdir test
touch test/.clang_complete
# open a .cpp file inside test directory by Spacemacs
```

**Comment by abingham** [comment]
Sorry for the delay. I've copied your spacemacs config, and I am seeing the same behavior as you. Adding an empty `.clang_complete` seems to break ycmd. I have no explanation for this. I think you should definitely check with the clang developers just to see if this a known issue.

**Comment by abingham** [comment]
@Valloric We're experiencing a strange problem with clang completion. The short version is this: it seems that if we put an empty `.clang_complete` in a directory with C++ source files, then ycmd stops working. If we remove `.clang_complete`, ycmd starts working again. Does this sound familiar at all?

**Comment by Valloric** [comment]
@abingham Never heard of it. Utterly bizarre! Nothing in ycmd needs such a file. Could be something in libclang, though I'd find it quite surprising. The only `.clang_complete` file I know of is a config file used by this plugin: https://github.com/Rip-Rip/clang_complete

It serves the same purpose as ycmd's `.ycm_extra_conf.py`, but obviously nothing in ycmd should care at all about such a file.

@mssun Do you have the clang_complete plugin installed? If yes, please try to remove it from Vim and see if that helps. It shouldn't since I can't imagine how it could affect ycmd, but it's the only idea I have.

@micbou @puremourning @vheon @r4nt Any ideas?

**Comment by vheon** [comment]
I have a feeling that this is a problem with Spacemacs. This does not happen in vim using YCM.

**Comment by micbou** [comment]
Same as @vheon, no issue with Vim when adding an empty `.clang_complete` file.

**Comment by micbou** [comment]
I think this is an issue with the C/C++ contribution layer of spacemacs. From the [documentation](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/c-c%2B%2B#company-clang-and-flycheck):

> This layer adds some fancy improvements to company-clang. It includes a hook to load a projects .clang_complete file, which is just a text file with one clang flag per line, a format also used by other text editor clang plugins.

**Comment by abingham** [comment]
Ah ha...it looks like you're right! In `layers/+tools/ycmd/packages.el:30` the ycmd init code checks to see if `ycmd-global-config` is already set; if not, it sets it to a `global_conf.py` which is included with spacemacs. That `global_conf.py` specifically looks for `.clang_complete` and, if found, uses it for compiler flags. Good catch, @micbou.

This is definitely questionable behavior. At the very least I would have liked to have a message printed indicating what was being done.

@mssun: if you set `ycmd-global-config` to something (probably anything...even a file that doesn't necessarily exist), do things start working?

(NB: I've had some wine this evening, so any typos and/or gaping logical errors are not my fault. In wine, truth...but not always clarity of thought.)

**Comment by mssun** [comment]
Many thanks to all of you.

@abingham I think you got the root cause.

If I set `ycmd-global-config` to an existing legit config file, it start working even with an empty `.clang_complete`. But, if pointing to a non-existing file, still got `Ycmd completion unavailable while parsing is in progress.` error. Is this normal?

I will report this bug to Spacemacs, I am sorry to introduce so much trouble to you guys. Anyway, thank you so much.

**Comment by abingham** [comment]
@mssun Thanks for your patience getting this sorted! I suppose an empty flags list *can* be correct, so spacemacs isn't entirely in the wrong here. We're just seeing some IMO surprising emergent behavior.

I think this discussion does point to at least one weakness in emacs-ycmd, which is that we shouldn't be reporting "parsing still in progress" when, in fact, parsing has failed. We need to detect that there's a problem and report that to the user. I'll create a new defect to address this.

I'm going to close this issue, but if you feel that it's not really done, reopen it and tell me what needs to be resolved.
