### ISSUE TITLE
About `ycmd-goto-definition' in C/C++

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abingham/emacs-ycmd#230]
Doing `ycmd-goto-declaration` indeed jumps to the correct location even in system headers, thanks to `#include` directives.  However, I assume that doing `ycmd-goto-definition` properly is more troubling as it should know where to look for source files (if the definition is not in the same file).  Do you guys know how to tell YCMD where to look for source files?  I'm asking because `ycmd-goto-definition` does nothing for me.

**Comment by ptrv** [comment]
Hi @Alexander-Shukaev 

Unfortunately `ycmd-goto-definition` for C-family languages only works in certain situations. It works when the definition of the symbol is in the current translation unit.
It works for example when you wnat to jump to a definition of a function in the same cpp file.

You can read bout this issue in the [YouCompleteMe README](https://github.com/Valloric/YouCompleteMe/blob/master/README.md#the-gotodefinition-subcommand).

**Comment by Alexander-Shukaev** [comment]
Hey @ptrv, thanks for your quick response.  I guess this one can be closed now.
