### ISSUE TITLE
Tests should report if ycmd can't be found.

### ISSUE THREAD

**Issue by abingham** [abingham/emacs-ycmd#239]
Right now, if we can't find ycmd (e.g. because we've misconfigured the path) while running tests, it's reported as a timeout. It would be better if we more accurately reported that ycmd couldn't be found.

**Comment by ptrv** [comment]
Added some checks for python and ycmd path in commit 3005b49176ff3315ba4cc7893fff42ce034d6e80

I changed the travis build configuration in order to run with sudo on the server (legacy mode) and the test run fine now. See [here](https://travis-ci.org/ptrv/emacs-ycmd/builds/98535104).
