### ISSUE TITLE
Better detection of failed compilation

### ISSUE THREAD

**Issue by abingham** [abingham/emacs-ycmd#242]
In some cases it appears that we fail to detect a broken compilation. Instead of telling the user that a file can't be compiled for some reason (e.g. because of bad path configuration, bad flag files, or something like that), we tell them that "parsing is still in progress". I think we just get stuck in the "parsing" mode on the client end. We need to better detect when things go awry on the server.

This really came to light in #228, [a discussion of problems with spacemacs](https://github.com/abingham/emacs-ycmd/issues/228#issuecomment-167386899).

**Comment by ptrv** [comment]
@abingham I started working on exception handling improvements. I'll start a PR soon.

**Comment by ptrv** [comment]
Fixed by #243

**Comment by ptrv** [comment]
Closing this for now because #243 was merged. Let's reopen if we find other issues.
