### ISSUE TITLE
Mark all buffers when the server has errors

### ISSUE THREAD

**Issue by abingham** [abingham/emacs-ycmd#246]
Right now when we detect errors in the server, we mark the proximal buffer with an error status. However, we don't mark any other buffers that are also affected, i.e. all other buffers that use ycmd. It might be nice to do so.

We would have to consider at least a few scenarios:

1. Marking existing buffers when the server is found to have errors
2. Unmarking existing buffers when the server is corrected/restarted/whatever.
3. Marking *new* buffers that are opened after the server is found to have errors.

This is all possible, I think, though I wonder how important it really is vs. the amount of extra code it requires.

**Comment by ptrv** [comment]
I noticed other incorrect states when we cannot connect to the ycmd server. In some functions we only check for whether `ycmd-mode` equals `t` and then we reset the status again to unparsed. Also the function `ycmd-running?` returns `t` even if we could not connect to the server because the process buffer is still there.

**Comment by abingham** [comment]
This is going to be an interesting issue. I thought a bit about marking other buffers when we detect an error, and it's not simple. An error in one buffer may be caused by bad flags for that file only; we can't assume immediately that the failure means anything for any other buffer.

On the other hand, if we time out when starting the server because we don't see/can't parse the port number, then all buffers are affected. I guess we really have two levels of state: buffer-specific and all ycmd-mode buffers.

Your last point is interesting. Right now `ycmd-running?` is just reporting whether there's a process running, but not whether that process seems "healthy". It doesn't look like we kill the process if startup times out, so we can have a broken-but-running server. Perhaps this is a hole we need to plug.

I have other things I need to focus on right now, unfortunately, but I'm happy to help you devise a more comprehensive strategy for sorting this all out.

**Comment by ptrv** [comment]
For now, as you said marking all buffers `errored` makes only sense when we cannot connect to the server. We should mark all buffers only in that case.

We can fix `ycmd-running?` by deleting the process if we timed out.

I am happy to look into the issues.

**Comment by ptrv** [comment]
See PR #247

> 1. Marking existing buffers when the server is found to have errors

Done

> 2. Unmarking existing buffers when the server is corrected/restarted/whatever.

Done

> 3. Marking new buffers that are opened after the server is found to have errors.

Happens automatically because when we open a new buffer, `emacs-ycmd` tries to
parse and and gets and error.

**Comment by ptrv** [comment]
Fixed with PR #247
