### ISSUE TITLE
Can't show ObjC function parameters in company tip window

### ISSUE THREAD

**Issue by chaozhn** [abingham/emacs-ycmd#248]
Thanks for your plugin firstly. I tried to configure it for objective-c language. Currently, the company tip window can be showed when I input some function name prefix, but the function parameters can not showed in the tip window. I don't know why and how to configure to show the full function definition in tip window, could you please help me? 
This is my **ycmd** and **company** configuration:
````
(defun my-ycmd-config()
  ;; ycmd setting
  ;(setq ycmd--log-enabled nil)
  ;; (setq ycmd-force-semantic-completion t)
  (cond
   ((spacemacs/system-is-mac)
    (set-variable 'ycmd-server-command '("python" "/Users/chao/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd"))
    (set-variable 'ycmd-global-config "/Users/chao/.ycm_extra_conf.py")
   )
   ((spacemacs/system-is-linux))
  )
  (ycmd-mode)

  ; company-ycmd settings
  (company-ycmd-setup)
  (company-quickhelp-mode 1)
  (custom-set-variables
   '(company-require-match nil)
   '(company-auto-complete nil)
   '(company-idle-delay 0)
   '(company-show-numbers t)
   '(company-tooltip-minimum-width 50)
   '(company-minimum-prefix-length 1)
  )

  ; flycheck settings
  (flycheck-ycmd-setup)
)
````
Thanks a lot!

**Comment by ptrv** [comment]
Hi @chaozhn 

Thanks for reporting the issue. At the moment ObjC support is pretty basic and showing function parameters is not implemented.

PR #249 implements better annotation support for ObjC.

Since I don't have a Mac setup for development right now, I cannot test it. It would be really great if you could test the branch from the PR and get back to here and report if it works or not.

**Comment by ptrv** [comment]
@chaozhn Are you sure you are triggering semantic completion and not only identifier completion?

**Comment by ptrv** [comment]
@chaozhn Did you have a chance to test the latest version of the `company-ycmd.el` file from this PR?
