### ISSUE TITLE
Check ycmd is not running correctly

### ISSUE THREAD

**Issue by manishxbhatia** [abingham/emacs-ycmd#254]
I installed emacs-ycmd and ycmd.
My ycmd command is 
(set-variable 'ycmd-server-command '("python" "~/git/ycmd/ycmd/ycmd"))
The server appears to start fine. (Though I cannot see the server logs.)

I copied the .ycm_extra_conf.py file in emacs-ycmd to my project directory and set the ycmd-extra-conf-whitelist
(set-variable 'ycmd-extra-conf-whitelist '("~/code/vatic/*"))

The file gets loaded when I open a .cc file in my project (as there is a popup and I say yes). The *ycmd-server* buffer in emacs doesn't show any errors.

However, after this, ycmd doesn't do anything. Even when I deliberately introduce a syntax error in the code it doesn't show any errors / warnings. It never provides any completions. I can't figure out the problem. The only thing I see in the *ycmd-server* buffer is:

2016-01-09 20:51:47,266 - DEBUG - Event name: FileReadyToParse
2016-01-09 20:51:47,266 - INFO - Adding buffer identifiers for file: /home/bhatia/code/vatic/quote.cc
2016-01-09 20:51:47,824 - INFO - Received health request
2016-01-09 20:51:57,238 - INFO - Received event notification
2016-01-09 20:51:57,238 - DEBUG - Event name: FileReadyToParse
2016-01-09 20:51:57,238 - INFO - Adding buffer identifiers for file: /home/bhatia/code/vatic/quote.cc
2016-01-09 20:52:00,322 - INFO - Received event notification
2016-01-09 20:52:00,322 - DEBUG - Event name: FileReadyToParse
2016-01-09 20:52:00,322 - INFO - Adding buffer identifiers for file: /home/bhatia/code/vatic/quote.cc
2016-01-09 20:52:17,824 - INFO - Received health request

Any help with debugging will be appreciated.

**Comment by manishxbhatia** [comment]
I turned on debugging in ycmd-request and fixed the .ycm_extra_conf.py file to include system headers.
ycmd server is now returning data related to errors. However, neither flycheck nor ycmd is doing anything with the errors.

Error data from *Messages* buffer, which shows integration with ycmd server is working. But emacs is not marking the errors at all.

REQUEST [debug] data = [((fixit_available . :json-false) (location_extent (end (line_num . 6) (column_num . 9) (filepath . /home/bhatia/code/vatic/main.cc)) (start (line_num . 6) (column_num . 5) (filepath . /home/bhatia/code/vatic/main.cc))) (location (line_num . 6) (column_num . 5) (filepath . /home/bhatia/code/vatic/main.cc)) (ranges . []) (text . use of undeclared identifier 'cout') (kind . ERROR)) ((fixit_available . :json-false) (location_extent (end (line_num . 8) (column_num . 7) (filepath . /home/bhatia/code/vatic/main.cc)) (start (line_num . 8) (column_num . 3) (filepath . /home/bhatia/code/vatic/main.cc))) (location (line_num . 8) (column_num . 3) (filepath . /home/bhatia/code/vatic/main.cc)) (ranges . []) (text . use of undeclared identifier 'cout') (kind . ERROR))]
REQUEST [debug] symbol-status = success
REQUEST [debug] Executing complete callback.
Mark set
Making completion list...
user-error: No more Flycheck errors

**Comment by manishxbhatia** [comment]
I turned on flycheck - using flycheck.el.  Flycheck gives the errors.
However, ycmd is still not providing completions. I expect a drop down box of possible completions.
For example. I have lines:
int token = 20;
tok

If I run ycmd-display-completions at the end of 2nd line, I get:

((completion_start_column . 3)
 (completions .
	      [((extra_menu_info . "[ID]")
		(insertion_text . "token"))])
 (errors .
	 []))

So the ycmd-server is returning token as a completion. But ycmd is not showing any dropox for me to select.

**Comment by abingham** [comment]
Are you using `company` and `company-ycmd` to display the completions? `ycmd` by itself doesn't do any sort of display (beyond the `ycmd-display-completions` command which you already found).

**Comment by manishxbhatia** [comment]
Thanks for the info. And thanks a lot for this github project!

I started company-ycmd and it works really well.  We should update the documentation to reflect this.

Regards
Manish

**Comment by manishxbhatia** [comment]
Closing this issue since everything is resolved.

**Comment by abingham** [comment]
OK, great! And thanks for the feedback on the setup instructions. I've added a bit of text to the README that's more explicit about using company-ycmd. Take a look at it and let me know if you think it's sufficient.
