### ISSUE TITLE
Error while checking syntax automatically

### ISSUE THREAD

**Issue by izuo** [abingham/emacs-ycmd#261]
Hi, I meet a problem with flycheck-ycmd:
![error_ycmd](https://cloud.githubusercontent.com/assets/8336146/12751166/7abdd14e-c9f6-11e5-8fd5-70358faa24d5.png)
and my config is:
```emacs-lisp
(prelude-require-packages
 '(ycmd
   company-ycmd
   flycheck-ycmd))

(use-package ycmd
  :init
  (add-hook 'c++-mode-hook 'ycmd-mode)
  (set-variable 'ycmd-server-command '("python" "/home/izuo/.ycmd/ycmd"))
  (set-variable 'ycmd-global-config "/home/izuo/.ycmd/cpp/ycm/.ycm_extra_conf.py")
  :config
  (use-package company-ycmd
    :init
    (company-ycmd-setup))
  (use-package flycheck-ycmd
    :init
    (flycheck-ycmd-setup))
  )
(when (not (display-graphic-p))
  (setq flycheck-indication-mode nil))

(provide 'custom-ycmd)
```
who can help to see this issue?

**Comment by ptrv** [comment]
Is everything up to date? Also `ycmd`?

Have you tried to remove your ycmd related *.elc files?

Looks like one of `ycmd.el` or `flycheck-ycmd.el` is not up to date?

**Comment by izuo** [comment]
@ptrv  Thanks, I've had the latest ```flycheck-ycmd.el```, and the problem has been solved by recomplie *.elc files in ```flycheck-ycmd-20160114.229/```.

**Comment by ptrv** [comment]
Great! I am glad we could resolve the issue.
