### ISSUE TITLE
Synchronous Requests

### ISSUE THREAD

**Issue by cartolari** [abingham/emacs-ycmd#264]
I've been using emacs-ycmd recently and found that sometimes the company popup does not appear (generally when I type too fast).
Another problem I've seen is that the company completion window keeps flickering as I type. Maybe not related but it happens to me only with async backends.
So trying to improve this I changed emacs-ycmd to do synchronous requests (completely removing deferred), I know this has the possibility to block Emacs and make the emacs-ycmd unsuitable to use, but instead what I've seen is a much better responsiveness with always instantly available completions. Doing synchronous requests didn't block Emacs, probably because ycmd is fast enough to support this scenario.
I've tested it on a I7 4500U running on Ubuntu 15.10 with Emacs 25.1 from the ubuntu-elisp ppa.

So the real question I have, wouldn't be better if the completion requests were synchronous since ycmd was built with performance in mind to support these scenarios?

**Comment by abingham** [comment]
For the majority of users this change would probably work just fine. In the case of certain C++ users, though, synchronous requests would be disastrous. As fast as ycmd itself is, the compilation of large C++ files can take 10s of seconds in some cases, and we don't want to block for that.

If the user experience improves as much as you say, though, I'd be more than happy to consider supporting sync and async modes. I don't know how much extra code that would add, but perhaps we could factor the code in a relatively DRY way.

@ptrv What are your thoughts on this?

**Comment by ptrv** [comment]
For C++, synchronous requests are really bad, as @abingham already pointed out. I think we should **not** go for synchronous requests. The file parse request can take several seconds for large C++ project and would block emacs completely for that time.
I tried @cartolari's `synchronous_commands` branch and Emacs was not responsive for a short time after opening a C++ file.

I can reproduce the company popup behavior. When the backend is async, the popup is flickering a bit and with synchronous request it is not. But IMHO this is a minor cosmetic issue. I think also this is more a company issue.

@dgutov What do you think about this?

**Comment by cartolari** [comment]
Yes, I could reproduce the file locking in C++ by opening the ycmd source code.
What I've noticed from the vim client is that it provides identifier completion while ycmd is parsing the file, which I sync is the /event_notification call with the event "FileReadyToParse" right? Correct if I'm wrong, but maybe this call could be asynchronous while the /completions call could be synchronous. I didn't look into the vim client but it appears to be what it does.

Regarding company-mode flickering, this is not the only issue, some times when I type faster the completion popup simply does not appear unless I manually invoke company or type some more chars, so the problem is that sometimes the completion does not appear for company-ycmd.

So shouldn't we really go synchronous at least for the "/completions" request?

**Comment by dgutov** [comment]
> sometimes the company popup does not appear

That sounds like a bug. Please update Company to the latest version from MELPA. The current next-to-last commit might fix that.

> completion window keeps flickering as I type

That's currently unavoidable when a backend both uses the async convention and `no-cache` (the latter is necessary for fuzzy matching).

If that's a real problem, maybe `company-ycmd` can try a hybrid approach: fire an asynchronous request, sleep for e.g. 50 ms, see if the server has responded already, if yes, return completions, otherwise use the asynchronous convention.

Maybe something similar should be used in `company--fetch-candidates`. Someone should try that. I'm not really sure that using `sleep-for` during idle completion is the way to go, though.

**Comment by abingham** [comment]
I'm curious about the approach @cartolari mentions where we use async for the parse requests and sync for the completion requests, returning identifier completions during parsing. I see a few advantages to this approach:

1. Since the company flickering is unavoidable with async backends, we'd get rid of that. 
2. The code for completions would be simpler and easier to read.
3. Things might be a touch faster

But perhaps there are downsides to this I haven't though of.

**Comment by ptrv** [comment]
I have a experimental branch with synchronous get completions request https://github.com/ptrv/emacs-ycmd/tree/synchronous-completion-request

This was just a very quick solution. I'll investigate further.

**Comment by cartolari** [comment]
@dgutov the latest version from MELPA fixes the issue of the popup not showing sometimes for async backends, thanks.

@ptrv I've tested your branch and although Emacs doesn't block, the completions are somewhat laggy, maybe because of deferred:sync!.
What I've done to support synchronous requests without rewriting the request infrastructure of emacs-ycmd was advise(in fact, override) company-ycmd--candidates, though I don't know if it's a good idea to call sleep-for in completion as pointed out by @dgutov.

```elisp
(defvar company-ycmd--completed nil)
(defvar company-ycmd--result nil)
(defun company-ycmd--candidates-sync-advice (orig-fun prefix)
  "Do sync request in 'company-ycmd--candidates'"
  (setq company-ycmd--completed nil
        company-ycmd--result nil)
  (company-ycmd--get-candidates
   (lambda (candidates)
     (setq company-ycmd--result candidates
           company-ycmd--completed t)) prefix)
  (while (not company-ycmd--completed)
    (sleep-for 0.01))
  company-ycmd--result)
(advice-add 'company-ycmd--candidates
            :around #'company-ycmd--candidates-sync-advice)
```

**Comment by dgutov** [comment]
@cartolari Your advice-based solution must be similarly laggy as well, right? Because you also convert the requests into synchronous ones this way.

**Comment by cartolari** [comment]
I gave a look at the deferred:sync! code, it sleeps for 50ms, which I think it's too much for instant code completion.
My advice sleeps only for 10ms between the checks.

**Comment by dgutov** [comment]
Oh. If it's just that, you might want to file an issue at emacs-deferred, asking to move the interval length to a dynamic variable.

**Comment by cartolari** [comment]
@dgutov, sure it's a good idea to open the issue.
I didn't looked at the code before so I wasn't sure why it was slower.

**Comment by ptrv** [comment]
@cartolari So with setting the time lower in `deferred:sync!` you get the desired behavior?

**Comment by cartolari** [comment]
I checked again and deferred:sync! is less laggy (but still slower than the advice solution), if the sleep is slower, but it makes company flicker again, I think it's because of a sit-for call. If I remove it company doesn't flick any more.
So I think deferred:sync! would not be a solution.

**Comment by ptrv** [comment]
I updated the branch https://github.com/ptrv/emacs-ycmd/tree/synchronous-completion-request 

I noticed also that with `deferred:sync!` the flickering is still present.

I added @dgutov's suggestion for a hybrid solution

```lisp
(defun company-ycmd--candidates (prefix)
  "Candidates-command handler for the company backend."
  (with-timeout
      (0.05 (cons :async
                  (lambda (cb)
                    (company-ycmd--get-candidates-deferred prefix cb))))
    (company-ycmd--get-candidates-synchronously prefix)))
```

**Comment by cartolari** [comment]
@ptrv I see you removed the deferred:sync! call. I think your branch is fine, the completions show instantly and the hybrid solution will prevent Emacs from blocking.
Also the completion for C++ works more like Vim now, it provides identifier completion while ycmd is parsing the file and provides semantic completion when the parsing is done.

For me if emacs-ycmd works this way it's OK.
