### ISSUE TITLE
ERROR: Ycmd server timeout

### ISSUE THREAD

**Issue by windrg** [abingham/emacs-ycmd#268]
Hi I just followed the configuration from [Jeff's slides](http://files.meetup.com/18516996/presentation.pdf). However it shows an error "ERROR: Ycmd server timeout"
```

(eval-after-load "company-ycmd-autoloads"
     '(progn (company-ycmd-setup)))

(eval-after-load "ycmd-autoloads"
    '(progn
      (set-variable  'ycmd-server-command  '("python"))
      (add-to-list  'ycmd-server-command (
      expand-file-name "~/oss/emacs/ycmd/ycmd") t )

     (set-variable  'ycmd-global-config
                             (expand-file-name "~/oss/emacs/ycmd/cpp/ycm/. ycm_extra_conf.py"))
     (add-hook  'c++- mode-hook
                         (lambda  ()
                              (ycmd-mode)
                              (company-mode)))))
```
Could I get some advices from you why it does, plese?

**Comment by ptrv** [comment]
There is  a typo in your `ycmd-global-config` path. Remove the space between the `.` and `ycm_extra_conf.py`

**Comment by windrg** [comment]
Thanks but that was a mistake in the above, not my init.el. Could you please what else could be the culprit?

**Comment by abingham** [comment]
Could you post the contents of your `*ycmd-server*` buffer?

**Comment by windrg** [comment]
I've managed to launch `ycmd-server` after installing a python lib `future` by typing `sudo pip install future`.
However it still complains like this.

![screenshot from 2016-02-19 17 45 18](https://cloud.githubusercontent.com/assets/506484/13170688/423a2000-d731-11e5-870c-2d704ffa6c19.png)

Unfortunately `ycmd-show-debug-info` didn't give me anything.

**Comment by abingham** [comment]
That looks a lot like an error on the server. Have you checked with [`ycmd`](https://github.com/Valloric/ycmd)?

**Comment by windrg** [comment]
Could you please let me know how to check it?

**Comment by abingham** [comment]
Create an issue with that project instead of this project. We're only the emacs client for the server. You could probably post the same picture you've posted here since that shows the output from the server.

**Comment by windrg** [comment]
Thanks for your guide. It would've been nice if there were a sort of logging system inside of  `ycmd` itself. Anyhow thanks.

**Comment by abingham** [comment]
What do you mean by "logging inside of ycmd itself"? The server outputs lots of useful information (as you've seen), and you can control its logging level through command-line options.

**Comment by windrg** [comment]
yes, you're right. sorry for my misunderstanding. :-D

**Comment by abingham** [comment]
No worries, and I hope this gets sorted out. If this turns out to be a problem with `emacs-ycmd`, just re-open this issue. Good luck!

**Comment by abingham** [comment]
Actually, I think I might see the problem. Are you using python 2 to run the server? I *think* they've upgraded recent versions to python 3.
