### ISSUE TITLE
How to assign the ycmd-server-command on windows?

### ISSUE THREAD

**Issue by asdyjd** [abingham/emacs-ycmd#274]
enviroment: Win10,python3,spacemacs,ycmd layer.
I compiled YCMD correctly with command "python build.py --all".
I tried to set ycmd-server-command differently for several times.

 (set 'ycmd-server-command '("python" "d:/emacs/ycmd/ycmd/\__main\__.py"))
 (set 'ycmd-server-command '("python" "d:/emacs/ycmd/ycmd"))
 (set 'ycmd-server-command '("python" "d:/emacs/ycmd/"))

Something like these.
But the emacs says:File mode specification error: (error "ERROR: Ycmd server timeout")
What to do?

**Comment by ptrv** [comment]
Unfortunately I have no experience with running `emacs-ycmd` on Windows, but the `README` has an entry for windows.

Can you try specifying the server command something like this:

```
(set-variable 'ycmd-server-command '("c:/path/to/python.exe" "-u" "c:/path/to/ycmd"))
```

**Comment by asdyjd** [comment]
I figured out this problem.
(set 'ycmd-global-config "D:/emacs/ycmd/ycmd/default_settings.json")
(set 'ycmd-server-command '("python" "-u" "d:/emacs/ycmd/ycmd"))
The python is python2 instead of python3!
And the options_file is default_settings.json!

**Comment by ptrv** [comment]
I am glad you could set the correct `ycmd-server-command`.

The `ycmd-global-config` is **not** `default_settings.json`. It is a python file like the `.ycm_extra_config.py` you can find in the `ycmd` project.

**Comment by frank0512** [comment]
你这问题解决了吗?

**Comment by asdyjd** [comment]
WINDOWS下的解决了,但是现在LINUX下的有问题.

**Comment by frank0512** [comment]
嗯 我windows 和MAC的都解决了...
