### ISSUE TITLE
Error completing in non ycmd-file-type-map files

### ISSUE THREAD

**Issue by akirakyle** [abingham/emacs-ycmd#289]
Hi,
So I was trying to get completion working for files that are not in `ycmd-file-type-map` so that I could still use just the identifier based completer even for languages where there is no semantic completion (the substring match and ranking is so much better than just using `dabbrev`). I got this working by doing, for example for fortran, `(add-to-list 'ycmd-file-type-map '(f90-mode "fortran"))` where the string shouldn't need to matter since I believe it is just used as a key for ycmd to identify files of the same type and offer completions from all open files of that same type. This all works as expected and I get completions no problem. However I noticed that the `*ycmd-server*` output is reporting the following error every time a completion is started:
```
2016-03-27 01:40:27,661 - ERROR - No semantic completer exists for filetypes: [u'fortran']
Traceback (most recent call last):
  File "/Users/akyle/Developer/ycmd/ycmd/../ycmd/server_state.py", line 94, in FiletypeCompletionAvailable
    self.GetFiletypeCompleter( filetypes )
  File "/Users/akyle/Developer/ycmd/ycmd/../ycmd/server_state.py", line 89, in GetFiletypeCompleter
    current_filetypes ) )
ValueError: No semantic completer exists for filetypes: [u'fortran']
2016-03-27 01:40:27,661 - DEBUG - Using filetype completion: False
```
I'm still getting the completions just fine, but it seems like there may be some miscommunication with the server about what filetypes to get semantic completion for.

**Comment by ptrv** [comment]
As I understood we don't need to provide a filetype for non semantic completion filetype. If a filetype is not in the map, we set them to 'generic' in the ycmd request and identifier completion should just work. About the error I don't know exactly how to deal with, maybe we need to provide an additional flag to the ycmd request or maybe we need to just catch the error to not show up in the minibuffer.

**Comment by abingham** [comment]
I think @ptrv's analysis is correct. If you use the string "generic" rather than "fortran" in your call to `add-to-list`, does everything work as expected (i.e. without the error)? This might be the simplest solution.

Regarding the error message output: I think we should not try to hide it. That error output could come in very handy if e.g. we misspell something in `ycmd-file-type-map`. My fear is that if we manage to hide those diagnostics, we'll end up with some unnecesarily painful debugging sessions in the future.

**Comment by ptrv** [comment]
I can reproduce this error message when I try to get semantic completion for a filetype that does not support it. This happens after a semantic trigger or when `ycmd-force-semantic-completion` is set to `t`.

The error message can be ignored.

Closing this issue.
