### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by asdyjd** [abingham/emacs-ycmd#290]
I have compiled ycmd.But there is an error when running.

asdyjd@yujinding:~/.emacs.d/ycmd$ python ycmd --options_file /home/asdyjd/.emacs.d/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/asdyjd/.emacs.d/ycmd/ycmd/__main__.py", line 183, in <module>
    Main()
  File "/home/asdyjd/.emacs.d/ycmd/ycmd/__main__.py", line 153, in Main
    options, hmac_secret = SetupOptions( args.options_file )
  File "/home/asdyjd/.emacs.d/ycmd/ycmd/__main__.py", line 130, in SetupOptions
    user_options = json.loads( ReadFile( options_file ) )
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by abingham** [comment]
This is a problem with [ycmd itself](https://github.com/valloric/ycmd), not the emacs clilent. I think it's a problem with python 2 vs. python 3.

**Comment by micbou** [comment]
This is not an issue with ycmd. @asdyjd is trying to start ycmd by passing a `.ycm_extra_conf.py` file to the `--options_file` parameter. That's not how it works. emacs-ycmd should take care of that, probably by setting the `ycmd-server-command` variable:
```emacs
(set-variable 'ycmd-server-command '("python" "/path/to/ycmd/package"))
```

**Comment by asdyjd** [comment]
But emacs tell me "ycmd--start-server: ERROR: Ycmd server timeout"

(set 'ycmd-global-config "~/.emacs.d/ycmd/cpp/ycm.ycm_extra_conf.py")
(set 'ycmd-server-command '("python" "/path/to/ycmd/package"))

**Comment by abingham** [comment]
@asdyjd Can you post the contents of the `*ycmd-server*` buffer when you see this error? That will help us sort this out.

**Comment by ptrv** [comment]
It looks like the ycmd-server command is not set properly. Notice the path to ycmd.

**Comment by asdyjd** [comment]
Now I set the variables as this:
(set 'ycmd-global-config "/home/asdyjd/.emacs.d/ycmd/cpp/ycm/.ycm_extra_conf.py")
(set 'ycmd-server-command '("python" "/home/asdyjd/.emacs.d/ycmd/ycmd"))
(add-hook 'after-init-hook 'global-ycmd-mode)

The emacs tell me:
Loading /home/asdyjd/.emacs.d/layers/+tools/ycmd/packages.el (source)...
YCMD won't work unless you set the ycmd-server-command variable to the path to a ycmd install.
Loading /home/asdyjd/.emacs.d/layers/+tools/ycmd/packages.el (source)...done
Making url-show-status local to  *http 127.0.0.1:46005* while let-bound!
REQUEST [error] Error from parser json-read: (end-of-file)
REQUEST [error] Error (parse-error) while connecting to http://127.0.0.1:46005/event_notification.
REQUEST [error] Error from parser json-read: (end-of-file)
REQUEST [error] Error (parse-error) while connecting to http://127.0.0.1:46005/event_notification.
REQUEST [error] Error from parser json-read: (end-of-file)
REQUEST [error] Error (parse-error) while connecting to http://127.0.0.1:46005/completions.
deferred error : (wrong-type-argument number-or-marker-p nil)
REQUEST [error] Error from parser json-read: (end-of-file)
REQUEST [error] Error (parse-error) while connecting to http://127.0.0.1:46005/completions.
deferred error : (wrong-type-argument number-or-marker-p nil)
REQUEST [error] Error from parser json-read: (end-of-file)
REQUEST [error] Error (parse-error) while connecting to http://127.0.0.1:46005/completions.
deferred error : (wrong-type-argument number-or-marker-p nil)

That's about all emacs tell me in the *Messages* buffer.And there is no *ycmd-server* buffer.
@abingham

**Comment by abingham** [comment]
Is it not working for you? The server appears to be running now.

**Comment by ptrv** [comment]
Closing the issue since the last post of the server window output shows that the server is running fine and the initial error was due to not setting the correct options file.
