### ISSUE TITLE
Cannot Complete C++ Standard Lib's Function and Other

### ISSUE THREAD

**Issue by RanTaimu** [abingham/emacs-ycmd#291]
Such as ‘vector’ ‘scanf’ ‘printf’.

And when I open a '.cpp' file which include a '.h' file, it cannot aware of functions definded in '.h' file at first. Only after I access to the '.h' file and back to '.cpp' file, the completion worked.

Am I missing some configuration steps?

OS: Ubuntu 14.04 LTS on VMWare Virtualbox
Emacs Version: 24.5.1 with spacemacs

*ycmd-server* buffer:
```
`2016-04-04 22:51:39,491 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
serving on http://127.0.0.1:57359
2016-04-04 22:51:40,945 - INFO - Received event notification
2016-04-04 22:51:40,947 - DEBUG - Event name: FileReadyToParse
2016-04-04 22:51:40,948 - INFO - Adding buffer identifiers for file: /home/rt/Desktop/TestEmacs/src/main.cpp
2016-04-04 22:51:40,961 - INFO - Received event notification
2016-04-04 22:51:40,962 - DEBUG - Event name: FileReadyToParse
2016-04-04 22:51:40,962 - INFO - Adding buffer identifiers for file: /home/rt/Desktop/TestEmacs/src/main.cpp
Traceback (most recent call last):
  File "/home/rt/Software/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/home/rt/Software/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/home/rt/Software/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 106, in wrapper
    return callback( *args, **kwargs )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/handlers.py", line 79, in EventNotification
    event_handler )( request_data )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 318, in OnFileReadyToParse
    flags = self._FlagsForRequest( request_data )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 381, in _FlagsForRequest
    return self._flags.FlagsForFile( filename, client_data = client_data )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/completers/cpp/flags.py", line 74, in FlagsForFile
    module = extra_conf_store.ModuleForSourceFile( filename )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/extra_conf_store.py", line 54, in ModuleForSourceFile
    return Load( ModuleFileForSourceFile( filename ) )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/extra_conf_store.py", line 65, in ModuleFileForSourceFile
    if Load( module_file ):
  File "/home/rt/Software/ycmd/ycmd/../ycmd/extra_conf_store.py", line 140, in Load
    if not _ShouldLoad( module_file ):
  File "/home/rt/Software/ycmd/ycmd/../ycmd/extra_conf_store.py", line 123, in _ShouldLoad
    raise UnknownExtraConf( module_file )
UnknownExtraConf: Found /home/rt/Desktop/TestEmacs/.ycm_extra_conf.py. Load? 

(Question can be turned off with options, see YCM docs)
Traceback (most recent call last):
  File "/home/rt/Software/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/home/rt/Software/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/home/rt/Software/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 106, in wrapper
    return callback( *args, **kwargs )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/handlers.py", line 79, in EventNotification
    event_handler )( request_data )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 318, in OnFileReadyToParse
    flags = self._FlagsForRequest( request_data )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 381, in _FlagsForRequest
    return self._flags.FlagsForFile( filename, client_data = client_data )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/completers/cpp/flags.py", line 74, in FlagsForFile
    module = extra_conf_store.ModuleForSourceFile( filename )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/extra_conf_store.py", line 54, in ModuleForSourceFile
    return Load( ModuleFileForSourceFile( filename ) )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/extra_conf_store.py", line 65, in ModuleFileForSourceFile
    if Load( module_file ):
  File "/home/rt/Software/ycmd/ycmd/../ycmd/extra_conf_store.py", line 140, in Load
    if not _ShouldLoad( module_file ):
  File "/home/rt/Software/ycmd/ycmd/../ycmd/extra_conf_store.py", line 123, in _ShouldLoad
    raise UnknownExtraConf( module_file )
UnknownExtraConf: Found /home/rt/Desktop/TestEmacs/.ycm_extra_conf.py. Load? 

(Question can be turned off with options, see YCM docs)
2016-04-04 22:51:42,524 - INFO - Received extra conf load request
2016-04-04 22:51:43,444 - INFO - Received extra conf load request
2016-04-04 22:51:43,497 - INFO - Received event notification
2016-04-04 22:51:43,498 - DEBUG - Event name: FileReadyToParse
2016-04-04 22:51:43,498 - INFO - Adding buffer identifiers for file: /home/rt/Desktop/TestEmacs/src/main.cpp
2016-04-04 22:51:43,502 - INFO - Received event notification
2016-04-04 22:51:43,502 - DEBUG - Event name: FileReadyToParse
2016-04-04 22:51:43,502 - INFO - Adding buffer identifiers for file: /home/rt/Desktop/TestEmacs/src/main.cpp
Traceback (most recent call last):
  File "/home/rt/Software/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/home/rt/Software/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/home/rt/Software/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 106, in wrapper
    return callback( *args, **kwargs )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/handlers.py", line 79, in EventNotification
    event_handler )( request_data )
  File "/home/rt/Software/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 322, in OnFileReadyToParse
    with self._files_being_compiled.GetExclusive( filename ):
  File "/home/rt/Software/ycmd/ycmd/../ycmd/completers/cpp/ephemeral_values_set.py", line 63, in __enter__
    raise RuntimeError( ALREADY_PARSING_MESSAGE )
RuntimeError: File already being parsed.
2016-04-04 22:52:09,553 - INFO - Received health request
2016-04-04 22:52:39,554 - INFO - Received health request`
```
my part of the .spacemacs configuration:
```
`(defun dotspacemacs/user-init ()
  "Initialization function for user code.
It is called immediately after `dotspacemacs/init', before layer configuration
executes.
 This function is mostly useful for variables that need to be set
before packages are loaded. If you are unsure, you should try in setting them in
`dotspacemacs/user-config' first."

  (setq-default c-default-style "bsd")
  (setq-default c-basic-offset 4)
  (setq-default tab-width 4)

  )

(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place you code here."



  (set-variable 'ycmd-server-command '("python" "/home/rt/Software/ycmd/ycmd"))
  (add-hook 'c-mode-hook 'ycmd-mode)
  (add-hook 'python-mode-hook 'ycmd-mode)
  (setq-default ycmd-request-message-level -1)

  ;; Bind clang-format-region to C-M-tab in all modes:
  ;(global-set-key [C-M-tab] 'clang-format-region)
  ;; Bind clang-format-buffer to tab on the c++-mode only:
  ;(add-hook 'c++-mode-hook 'clang-format-bindings)
  ;(defun clang-format-bindings ()
  ;  (define-key c++-mode-map [tab] 'clang-format-buffer))

  ; resolve the comflict between ycmd and company-c-headers
  ;(setq company-backends-c-mode-common '((company-c-headers
  ;                                        company-ycmd
  ;                                        company-dabbrev :with company-yasnippet)))

  )`

dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     (auto-completion :variables
                      auto-completion-return-key-behavior 'complete
                      auto-completion-tab-key-behavior 'cycle
                      auto-completion-complete-with-key-sequence nil
                      auto-completion-complete-with-key-sequence-delay 0.1
                      auto-completion-private-snippets-directory nil)
     ycmd
     ;; better-defaults
     emacs-lisp
     (c-c++ :variables
            ;c-c++-enable-clang-support t
            c-c++-default-mode-for-headers 'c++-mode
            )
     (python :variables
             python-test-runner 'pytest
             python-enable-yapf-format-on-save t
             )
     ;; git
     ;; markdown
     org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     syntax-checking
     semantic
     gtags
     ;; version-control
     )
```

**Comment by abingham** [comment]
Can you post the contents of your `*ycmd-server*` buffer? It sounds like maybe you're just getting identifier-based completion, not actual C++-aware completion.

**Comment by RanTaimu** [comment]
@abingham 
Thanks to reply me!
I've updated the ycmd-server buffer's contents and posted part of my .spacemacs.

**Comment by abingham** [comment]
What is your value for `ycmd-extra-conf-handler`?

**Comment by RanTaimu** [comment]
@abingham 
It's the default value 'ask

*** Welcome to IELM ***  Type (describe-mode) for help.
ELISP> (prin1 ycmd-extra-conf-handler)
ask
ask
ELISP>

**Comment by abingham** [comment]
Are you sure you've got an "extra conf" file that the ycmd server is loading which tells it how to compile your stuff? If ycmd can't compile your code, then it can't figure out non-identifier completions for it.

**Comment by RanTaimu** [comment]
@abingham
I use the 'YCM_Generator' to get the 'extra conf' file, and it seems to run normally :

**~/Desktop/TestEmacs/build$ ~/Software/YCM-Generator/config_gen.py ~/Desktop/TestEmacs/
Running cmake in '/tmp/tmpyGs4ns'...
$ cmake /home/rt/Desktop/TestEmacs

Running make...
$ make -i -j2

Cleaning up...

Build completed in 1.48 sec

Collected 0 relevant entries for C compilation (0 discarded).
Collected 3 relevant entries for C++ compilation (0 discarded).
Created YCM config file with 1 C++ flags**

And my test project just has one 'taaa.h' file in 'include' folder and 'main.cpp' 'taaa.cpp' in root folder.

The conf file : 

# Generated by YCM Generator at 2016-04-05 19:24:59.037443

# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
    '-x',
    'c++',
    '-I/home/rt/Desktop/TestEmacs/include',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }

**Comment by abingham** [comment]
Is emacs asking you about loading your extra conf? And if so, are you saying yes?

**Comment by RanTaimu** [comment]
@abingham 

Yes; Yes
When the 'ycmd-extra-conf-handler' is 'ask, there do has an ask and I said yes.
Then I change the value to 'load.

AND, the syntax checking works very well......

**Comment by abingham** [comment]
I have to admit that I'm not sure what's going on. Based on the server output you posted, it looks like the server is at least trying to compile the code in main.cpp. If that file doesn't compile then that might explain what you're seeing.

**Comment by RanTaimu** [comment]
@abingham 
OK... I think I should write a much simple program to figure out the problem...
Thank you all the same !

**Comment by RanTaimu** [comment]
@abingham 

Oh.... I write a project from scratch, and this time the functions of ycmd worked !!

But there still a problem: even though I added "using namespace std;" ycmd still cannot complete 'vector' 'cout' 'endl' etc. But when I added the prefix  'std::', the completion appeared. Is that normal ?

**Comment by ptrv** [comment]
@RanTaimu It is normal. C++-aware completion is only available after a semantic trigger like '.', '->' or '::'. If there is no preceding semantic trigger you only get identifier-based completion. However you can force c++-aware completion without semantic trigger by calling ycmd-force-semantic-completion. This can be slow for large projects.

**Comment by RanTaimu** [comment]
@ptrv 
OK. Thanks for your guidance !
