### ISSUE TITLE
cl--assertion-failed: Assertion failed: (or (= (buffer-size tar-data-buffer) (buffer-size)) (eq tar-data-swapped (> (buffer-size tar-data-buffer) (buffer-size))))

### ISSUE THREAD

**Issue by zwb-ict** [abingham/emacs-ycmd#293]
I'm on OSX emacs gnu 25.1.50.1, when I run
```
package-install company-ycmd
```
I got error:

```
cl--assertion-failed: Assertion failed: (or (= (buffer-size tar-data-buffer) (buffer-size)) (eq tar-data-swapped (> (buffer-size tar-data-buffer) (buffer-size))))
```

**Comment by abingham** [comment]
I googled your error message and saw [this](https://github.com/syl20bnr/spacemacs/issues/4385). It sounds like you've got some networking/firewall problem associated with packages.

In particular, this might help:

> Set `dotspacemacs-elpa-https` to `nil` and ran `M-x package-install clj-refactor`. Looks like it worked.

**Comment by zwb-ict** [comment]
@abingham Thanks a lot. This sloved my problem.
