### ISSUE TITLE
Cannot open load file: no such file or directory, ycmd-request

### ISSUE THREAD

**Issue by ZzAntares** [abingham/emacs-ycmd#306]
Hi, I've installed this package from MELPA and just when doing `(require 'ycmd)` I'm getting:

```
Cannot open load file: no such file or directory, ycmd-request
```

Indeed this file is not anywhere in the package, so do I need an extra dependency? so far I got `company`, `company-ycmd` and `ycmd` installed.

Thanks for the help.

**Comment by ptrv** [comment]
This is strange. Do you have another (outdated) installation of `emacs-ycmd`? Or your Emacs config loads an outdated byte-compiled `emacs-ycmd`?

When you open the `ycmd.el`, does the `Package-Requires:` in line 6 contain `request` or `ycmd-request`?

We switched the dependency back to upstream `request` library and removed `ycmd-request` files from  the repository.

**Comment by ZzAntares** [comment]
Yes that was the issue, I did had an outdated version of ycmd, I've updated my package list and everything is working fine now, thanks!
