### ISSUE TITLE
FixIts on notes: emacs-ycmd applies all FixIts rather than offering a choice

### ISSUE THREAD

**Issue by puremourning** [abingham/emacs-ycmd#316]
Hi guys,

In https://github.com/Valloric/ycmd/pull/532, we added support to ycmd to provide FixIts from clang that are attached to 'notes' . These are often the sort of "did you mean xxx?" suggestions you get from clang on the command line, and occasionally include _multiple_ suggestions. The user is expected to only apply _one_ such suggestion.

I realise this is entirely my fault, but the current emacs-ycmd implementation (unless i'm missing something, or simply mistaken) is to apply *all* FixIts that are returned by the `FixIt` completer subcommand. This has the effect of applying *all* suggested FixIts, which is not what was intended.

## Example test case

in C++ file

```c++
int main()
{
    bool x;
    if ( x = true ) {

    }
}
```

You get a diagnostic on the '=' in the comparison, and we offer 2 possible suggestions. either wrap the assignment in `(...)` or use `==`. In the Vim client, we as the user which one to apply, but emacs-ycmd applies both, yielding correct but not intentional result:

```c++
int main()
{
    bool x;
    if ( (x == true) ) {

    }
}

```

I guess it would be better if emacs-ycmd could offer the user the list of FixIts to apply and select from? We can also make a change to ycmd to inform that a FixIt is a note if this would help (something i considered at the time of implementing it).

FWIW, here's a little video of what the Vim client does (in case it helps):

![ycm-fixit-multiple-choice2](https://cloud.githubusercontent.com/assets/10584846/17080247/e22636b8-511f-11e6-8202-5b89a370856b.gif)

I'm raising this because I don't have the skills to help out, sorry :).

**Comment by ptrv** [comment]
@puremourning Thanks for bringing this up! I haven't noticed the change in ycmd. I'll have a look into this and I'll come up with something.

Nice feature btw. :smile:

**Comment by ptrv** [comment]
@puremourning In order to distinct notes from multiple fixits on a line, can I rely on the fact that notes have the same location?

**Comment by puremourning** [comment]
Good question. Currently in the Vim client we don't distinguish.

We set the location of the FixIt to the location of its associated diagnostic. Diagnostics in clang are hierarchical, so while it might always _be the case_ that they share a location with their immediate siblings, I don't think it is guaranteed any way in the interface.

ycmd does *know* that a FixIt comes from a note (or strictly, a child diagnostic), so we could indicate that on the API, but currently we just flatten the hierarchy and return them all. :/

**Comment by ptrv** [comment]
I started with the implementation and the handling of the fixit data is more or less done, I am working on the Emacs specific integration.  I realized that it is not important to know whether the data is a note or not. Only the location is important and if the same location has multiple fixits then show a list instead of applying the chunk.
