### ISSUE TITLE
Function to reacquire flags (restart server)

### ISSUE THREAD

**Issue by quicknir** [abingham/emacs-ycmd#318]
Hi,

I've found that when I refresh my compile_commands.json file, which ycmd is using to get the flags for my files, I'm not able to get it to refresh to use the new flags. I run ycmd-clear-compilation-flag-cache, I turn ycmd-mode off and on, I close the file and re-open it, etc. The only thing that seems to work is restarting emacs. Is there some other way to do it? I assume that restarting the server would do it; I think that ycmd exposes such a command in vim, but it is not available seemingly in emacs.

Cheers.

**Comment by ptrv** [comment]
If you do `M-x ycmd-open` when the server is running, then the server gets restarted. The file is after that unparsed, you can see the `?` next to `ycmd` in the mode-line. So you need to `M-x ycmd-parse-buffer` to reparse.

**Comment by quicknir** [comment]
@ptrv Cool, thanks. I will give this a shot the next time I have this come up. I'll close for now and re-open only if this doesn't work. Thanks again!
