### ISSUE TITLE
Option to skip fixit confirmation

### ISSUE THREAD

**Issue by quicknir** [abingham/emacs-ycmd#319]
Title pretty much says it all. Personally I'd rather just apply the fixit right away, and then undo if there's a problem. I'd guess the code change would be trivial?

**Comment by ptrv** [comment]
There is the option `ycmd-confirm-fixit` which is by default set to `t`. You can change it then you don't have to confirm.

**Comment by quicknir** [comment]
Thanks, sorry, my bad!
