### ISSUE TITLE
Problem with non-ascii characters.

### ISSUE THREAD

**Issue by r4nt** [abingham/emacs-ycmd#323]
#include <string>

int main (int argc, char** argv) {
  std::string foo = "42°C";
}

Leads to errors in emacs 25.1.1. Related emacs bug:
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=24117#23

Modifying ycmd.el:1755 to use 'curl instead of 'url-retrieve works around the problem.

**Comment by ptrv** [comment]
Thanks for the report and for the workaround.

I tried out changing the `request-backend` to `curl` and all tests pass.

@abingham Was there a specific reason to explicitly use `url-retrieve` as `request-backend`?
The default value of `request-backend` is `curl` if it is installed and `url-retrieve` if the `curl` executable cannot be found. We could just use that or specify a variable in `ycmd` to only select the backend for `ycmd` requests.

**Comment by abingham** [comment]
That decision was probably part of the fallout from the huge struggles we had with `request` in the early part of development. Probably partly misconceptions on my part, partly something that seemed like a good idea at the time. If everything seems to work with `request`'s default value, then let's use that.
