### ISSUE TITLE
c++ constructor completion is not supported?

### ISSUE THREAD

**Issue by handrake0724** [abingham/emacs-ycmd#324]
I have installed emacs-ycmd.
When I type a class instance followed by a period, class member functions and variables can be listed by use of emacs-ycmd.
But the function of listing candidate constructor is not working when I declare a class instance.
i.e.) 
Lets assume that class A have two constructors as follows:
class A { 
public:  
A ();
A (int a);
A (int a, int b);
};

in the main function
int main(int argc, char** argv) {
  A a(
}

I want constructors to be listed when I type a follows by ( but it does not work.

**Comment by abingham** [comment]
I'm not sure if the underlying ycmd server gives us any results in this situation. In fact, [this](https://www.bountysource.com/issues/1123353-show-constructor-signatures-for-c) seems into indicate that perhaps it doesn't support constructors right now.

@Valloric What is the state of C++ constructor completion right now?

**Comment by Valloric** [comment]
For a line like `A a(`, if you force semantic completion after `a` (before the paren) ctor completion might work, depending on libclang. But I'm not entirely sure about that; ctor completion seems like a corner case. In this instance, you'd want param group completion, but ycmd is focused on _name_ completion; AFAIR we even collapse multiple overloads to one entry in the completion menu for YCM (not sure how emacs-ycmd handles the response).

**Comment by ptrv** [comment]
I tried out a forced semantic completion after `A a` but there was no semantic result. Same behavior in vim. @Valloric what do you mean by

> might work, depending on libclang

**Comment by Valloric** [comment]
@ptrv I meant it depends on what libclang decides are semantic completions at that point. We'll query libclang for semantic completions at that line & column, but it's up to libclang to decide what to return. So if libclang returns nothing here, then it doesn't support ctor completion for this use-case.

**Comment by ptrv** [comment]
Ok, I understand. Looks like libclang does not support ctor completion after the variable name.
If the cursor is after the class name, then a forced semantic completion returns the different ctor versions.

**Comment by abingham** [comment]
It sounds like this is resolved. @handrake0724, reopen it (with an explanation) if you feel otherwise.
