### ISSUE TITLE
activate travis-ci for this repo

### ISSUE THREAD

**Issue by ptrv** [abingham/emacs-ycmd#328]
It would be nice to have travis-ci integration for this repo to only be able to merge pull requests when tests are passing.

@abingham Could you setup emacs-ycmd on travis-ci.org and then activate the travis service in the repo settings?

**Comment by abingham** [comment]
Good idea. I'll try to get to it soon.

**Comment by ptrv** [comment]
Cool thanks!

**Comment by abingham** [comment]
@ptrv When you set up your travis build, did you have any problems with the dash package? It looks like my .travis.yml is the same as your (which builds successfully), but mine fails because it can't require dash: https://travis-ci.org/abingham/emacs-ycmd

**Comment by ptrv** [comment]
Looks odd. I'll have a look.

**Comment by abingham** [comment]
It seems like some old elc file is sticking around or something.

**Comment by ptrv** [comment]
In the `travis.yml` there is caching for the cask directory enabled. In my travis the builds were run successful because it didn't update dash for a while. I created a test branch and now it fails there too

**Comment by abingham** [comment]
Ah, right. I've started a build with a "make clean" at the start. If that doesn't do the trick, I'll disable the caching.

**Comment by ptrv** [comment]
The builds are still failing. I'll have a deeper look when I have more time

**Comment by ptrv** [comment]
Travis works fine now. Finally
