### ISSUE TITLE
emacs-ycmd cannot figure out port number

### ISSUE THREAD

**Issue by stanford-scs** [abingham/emacs-ycmd#330]
I'm using ycmd-20160809.355 from elpa on arch linux with emacs 24.5.1 and vim-youcompleteme-git. emacs-ycmd does not seem to be able to figure out the port number, and always dies with the error:

`REQUEST [error] Error (error) while connecting to http://127.0.0.1:0/shutdown.`

Note the port number of 0.  In my .emacs I set:

```
(setq ycmd-server-command
      '("python2" "-u" "/usr/share/vim/vimfiles/third_party/ycmd/ycmd"))
```

This leads to emacs-ycmd spawning commands like this:

`/usr/bin/python2 -u /usr/share/vim/vimfiles/third_party/ycmd/ycmd --options_file=/tmp/ycmd-options28261nwu --log=debug --keep_logfile --idle_suicide_seconds=10800`

However, when I run `(ycmd--create-options-file "blah")` and then manually execute such a command, I don't see any output of the form `serving on http://...`, so as expected `ycmd--server-actual-port` is always 0.  For example:

```
$ /usr/bin/python2 -u /usr/share/vim/vimfiles/third_party/ycmd/ycmd --options_file=/tmp/ycmd-options28261Nci --log=debug --keep_logfile --idle_suicide_seconds=10800
2016-08-10 15:53:23,778 - DEBUG - No global extra conf, not calling method YcmCorePreload
```
[After which it waits serving HTTP requests on a dynamically allocated port such as 35787, though it changes each time, so I have to discover it with a tool like lsof.]

I realize this must be a pretty basic problem, because clearly a lot of people use this package and yet it doesn't work at all for me.  However, I've lost a lot of time on this.  At the very least consider this a documentation request to give an example of an actually working configuration, because from the available materials I don't understand how this package is ever supposed to work.

**Comment by ptrv** [comment]
Hi,

it looks like your `vim-youcompleteme-git` installation is outdated. The `/shutdown` command has  been introduced in `ycmd` quite recently and your version does not support it.

I suggest to install from the `ycmd` [git repo](https://github.com/Valloric/ycmd) or update `vim-youcompleteme-git` package.

**Comment by stanford-scs** [comment]
I'm running youcompleteme from git, and it seems to support shutdown just fine.  Look at the port number in the URL:

`REQUEST [error] Error (error) while connecting to http://127.0.0.1:0/shutdown.`

The problem is that emacs never actually connects to ycmd, because it is trying to connect to TCP port 0.  So of obviously the /shutdown request to a non-existent HTTP server on non-existent TCP port 0 is failing...

**Comment by stanford-scs** [comment]
@ptrv Could my ycmd installation be *too* recent?  Because it doesn't seem to print out it's listening URL any more.  Can you suggest an older version of ycmd to try?

**Comment by ptrv** [comment]
When  did you install `vim-youcompleteme-git`? There was an issue in `ycmd` which has been fixed: https://github.com/Valloric/ycmd/pull/555

**Comment by stanford-scs** [comment]
I'm using git commit da5fb5aa2d25c5a5908d0dbb2ff8c83a7e1029ad, dated 5:16am this morning. It seems to be the latest.  Thanks.

**Comment by abingham** [comment]
I can't explain this. I fresh linux installation (ubuntu, not arch) and tried to recreate your scenario, but everything seems to work fine. At least, I've verified that ycmd is printing its port as expected. 

Is is possible that your shell is doing buffering somehow? 

I'd like to verify that ycmd is even getting to the point in the code that should print the info. I don't see how it would *not* get there, but it should be simple to rule out that line of investigation. At around [ycmd/wsgi_server.py:41](https://github.com/Valloric/ycmd/blob/master/ycmd/wsgi_server.py#L41), put an `assert False` or something to explicitly kill the server. If this isn't triggered when you run the server, then something is very fishy.

If it does die, then presumably something in the pipeline is preventing the `print` from displaying its output.

**Comment by ptrv** [comment]
I installed `vim-youcompletme-git` on my system, since I also run arch and it doesn't work here either. I you look into the file `/usr/share/vim/vimfiles/third_party/ycmd/ycmd/wsgi_server.py` doesn't have the print in the `Run` method. It's definitely not the latest version.

Please use the latest `ycmd` version from git for a working setup.

**Comment by ptrv** [comment]
Ok, i figured out the problem. `vim-youcompleteme-git` installs the latest `youcomplete` plugin, however the submodules are not pointing to the latest commits. So, `ycmd` is at 8b2f78acb4cc19a5ec4c9bbb8a60f97911d33d3c which is from 19 days ago, which does not contain a the fix to print the line `serving at http://...`

**Comment by stanford-scs** [comment]
Weird.  If I unpack the sources with `makepkg -o --skippgp` and cd to `src/ycmd`, I get:

```
$ git rev-parse HEAD
da5fb5aa2d25c5a5908d0dbb2ff8c83a7e1029ad
$
```
However, if I run `diff -u ycmd/wsgi_server.py /usr/share/vim/vimfiles/third_party/ycmd/ycmd/wsgi_server.py` indeed the print is missing.  It appears there are *two* copies of ycmd being checked out.  The one in `YouCompleteMe/ycmd` is a submodule that has the old version 8b2f78acb4cc19a5ec4c9bbb8a60f97911d33d3c.  So this is how I got confused about which version I was running.  Really sorry about that.

**Comment by ptrv** [comment]
@stanford-scs Could you make `ycmd` work?

**Comment by stanford-scs** [comment]
Yup, seems to work for me now.  For anyone else getting this problem on arch, I just manually updated ycmd in the `vim-youcompleteme-core-git` package by unpacking it (`yaourt -G vim-youcompleteme-core-git`), then going into `src/YouCompleteMe` and running `git submodule update --remote third_party/ycmd`.  After that 'makepkg -fei` installed a working ycmd daemon for me.  Thanks for your help, and sorry to have opened a non-issue.

**Comment by ptrv** [comment]
@stanford-scs no worries. I'm glad `ycmd` works for you  now.
