### ISSUE TITLE
libclang.dll assertion fail sometimes happen

### ISSUE THREAD

**Issue by zijianyue** [abingham/emacs-ycmd#332]
I have '-fexceptions' and '-DNDEBUG' in the .ycm_extra_conf.py file , why assertion still happened
 I'm working on WIN7 64bit, python2.7.12 is installed in c:/Python27/. LLVM 3.8.1

**Comment by abingham** [comment]
This sounds like a problem with ycmd, not the emacs bindings. Have you asked there?

**Comment by zijianyue** [comment]
no

**Comment by abingham** [comment]
What are your settings for ycmd-global-config, ycmd-extra-conf-whitelist, and ycmd-extra-conf-handler?

**Comment by zijianyue** [comment]
(set-variable 'ycmd-server-command '("python" "-u" "D:/ycmd/ycmd/"))
(set-variable 'ycmd-global-config "~/.ycm_extra_conf.py")
(setq ycmd-extra-conf-handler 'load)
And I didn't set ycmd-extra-conf-whitelist

**Comment by zijianyue** [comment]
I found this debug info in my "ycmd-server" buffer :
DEBUG - Global extra conf not loaded or no function YcmCorePreload

**Comment by abingham** [comment]
This is mysterious. Try changing your `ycmd-global-config` value to the full, absolute path to your extra config, i.e. replace "~" with the actual path. I don't think this should be an issue, but it's possible. 

Also, could you post the full contents of your `.ycm_extra_conf.py`? That might contain some clues.

**Comment by zijianyue** [comment]
Today I use the version of cbc0275296e96913db61168bf677fdacca192a4b, the issue happened rarely ,before this version it happed frequently

**Comment by zijianyue** [comment]
My global extra config content:
# Copyright (C) 2014 Google Inc.
#
# This file is part of ycmd.
#
# ycmd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ycmd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ycmd.  If not, see <http://www.gnu.org/licenses/>.

import os
import ycm_core

# These are the compilation flags that will be used in case there's no
# compilation database set (by default, one is not set).
# CHANGE THIS LIST OF FLAGS. YES, THIS IS THE DROID YOU HAVE BEEN LOOKING FOR.
flags = [
  '-std=c99',
  '-x',
  'c',
  '-fexceptions',               # no exception
  '-DNDEBUG',                   # no assert
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


# This is the entry point; this function is called by ycmd to produce flags for
# a file.
def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )
  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }

**Comment by abingham** [comment]
I'm not sure what could be happening then. It's really strange that it only happens sometimes; I would expect that you'd see problems all of the time or never. Assuming that you've got `ycmd-global-config` set correctly, it looks like things should work.

You could try calling `ycmd-toggle-log-enabled` to see if anything suspicious shows up in the logs.

**Comment by zijianyue** [comment]
My extra config of working project:
Only the content of flags is different with my global extra config. And I delete and modify some private stuff for our security policy.
flags = [
  # THIS IS IMPORTANT! Without a "-std=<something>" flag, clang won't know which
  # language to use when compiling headers. So it will guess. Badly. So C++
  # headers will be compiled as C headers. You don't want that so ALWAYS specify
  # a "-std=<something>".
  # For a C project, you would set this to something like 'c99' instead of
  # 'c++11'.
  '-std=c99',
  # ...and the same thing goes for the magic -x option which specifies the
  # language that the files to be compiled are written in. This is mostly
  # relevant for c++ headers.
  # For a C project, you would set this to 'c' instead of 'c++'.
  '-x',
  'c',
  '-Wno-cast-qual',
  '-Wno-gnu-zero-variadic-macro-arguments',
  '-Wno-deprecated-declarations', 
  '-Wno-disabled-macro-expansion', 
  '-Wno-float-equal', 
  '-Wno-global-constructors', 
  '-Wno-exit-time-destructors', 
  '-Wno-missing-prototypes', 
  '-Wno-padded', 
  '-ferror-limit=0',
  '-fexceptions',               # when exception occur , do not exit 
  '-DNDEBUG',                   # no assertion
  '-nostdinc',                  # do not use system default include path
  '-I',
  '.',
  '-I',
  'MP\\include',
  '-I',
  'OPEN/proto',
  '-include',
  'MP/incl.h',
  '-isystem',
  'D:/libheaders/gcc/include',
  '-isystem',
  'D:/libheaders/include',
  '-isystem',
  'D:/libheaders/include/linux',
  '-D_OS_=LINUX',
]

**Comment by zijianyue** [comment]
These two days, after using the latest version of emacs-ycmd, this issue disappeared, so I close it
