### ISSUE TITLE
Consider using homu.io for automatic test+merge

### ISSUE THREAD

**Issue by abingham** [abingham/emacs-ycmd#338]
[homu.io](http://homu.io/) seems to provide a nice layer to the github/travis system in which it does automatically does merges when a) humans have approved the change and b) tests are passing. This could be a nice addition to our current system.

**Comment by abingham** [comment]
I *think* this is set up now. There was some error during oauth stuff, but it shows homu as a collaborator now. Need to give it a test run.

**Comment by ptrv** [comment]
Oh cool. Using homu.io is a very good idea.

**Comment by abingham** [comment]
They seem to be having database connection issues or something right now. Attempts to enable homu integration result in a) the collaborator being added to the project and b) an error about a broken pipe. I figure we should just try later.

**Comment by abingham** [comment]
It looks like [homu.io is broken, and it may have been so since April](https://github.com/barosl/homu/issues/148).

**Comment by ptrv** [comment]
@abingham 

At  YCM and ycmd they have now a self hosted Homu instance and @Valloric would be so kind to add `emcas-ycmd` to this instance so we have also an integration bot. 
We therefore would need to add @zzbot as collaborator to this repo for push rights. 
Quote from @Valloric 

> you'll also need to add @zzbot as a collaborator to your repo, and since I own that account, you'd be transitively giving me push access; not that I'd ever use it, but I want to make it clear that you'll be entrusting your repo security with me
which you may not be comfortable with

What do you think?

**Comment by abingham** [comment]
I'm perfectly fine with @zzbot having push rights, esp. if it gives us a nice auto-merge workflow.

**Comment by abingham** [comment]
This all seems to work now :)
