### ISSUE TITLE
When the cursor is at the right boundary of word ,ycmd-goto can't work

### ISSUE THREAD

**Issue by zijianyue** [abingham/emacs-ycmd#341]
For example: pstAbc->uiAttr ,and the cursor is after the letter 'r', ycmd-goto can't jump to the definition.
BTW some other tools like semantic-ia-fast-jump and helm-gtags-find-tag support this.
Can emacs-ycmd add this support ,it can save one M-b stroke when I use M-f to move to the symbol that I want to ycmd-goto.

**Comment by abingham** [comment]
We could probably find a reasonable algorithm for doing this. `helm-gtags-find-tag` uses `thing-at-point` to figure out what the user is looking at,  but we don't really have that option. We essentially just send a bunch of information - buffer contents, current position, etc. - over to ycmd and ask it for an answer, so ycmd is responsible for figuring out what the user is looking at.

We'd probably have to find a heuristic for temporarily changing the position of `point` before sending the request. Perhaps something like this:
1. If there is a non-whitespace character at point, do nothing.
2. If there is whitespace at point, and if point is not at the start of the line then move back one space, send the request, and then move back to the original position.

I'm sure there's room for improvement there, but something like that might work.

**Comment by abingham** [comment]
@zijianyue I've just merged in a patch by @ptrv that should fix this issue:

    https://github.com/abingham/emacs-ycmd/pull/342

Try it now and let us know if it works for you.

**Comment by zijianyue** [comment]
Great , it works very well!
