### ISSUE TITLE
flycheck-ycmd broken with latest flycheck update

### ISSUE THREAD

**Issue by radupopescu** [abingham/emacs-ycmd#351]
The latest version of `flycheck` (`flycheck-20160912.814` from Melpa) makes the `:modes` parameter mandatory for all syntax checkers. `flycheck-ycmd` relies on `:predicate` and doesn't define any `:modes`.

**Comment by ptrv** [comment]
@radupopescu Btw, thanks for reporting

**Comment by radupopescu** [comment]
Thank you for the really quick fix!
