### ISSUE TITLE
Signals returned by the ycmd process are handled the same way as exit codes

### ISSUE THREAD

**Issue by micbou** [abingham/emacs-ycmd#352]
When the ycmd process is killed by a signal, emacs-ycmd considers the signal as an exit code, which leads to error messages completely unrelated to the reason why the server is terminated:
 - in issue #331, the ycmd server returns the SIGABRT signal, which is handled as an exit code of 6 and an error message about the ycm_core library imported with the wrong Python is shown to the user;
 - in issue #344, the ycmd server is terminated with the SIGKILL signal, which is interpreted as an exit code of 9. This is not a valid exit code so no specific message.

**Comment by ptrv** [comment]
Thanks for reporting. Yes indeed, we were handling signals same as exit code.

**Comment by abingham** [comment]
@micbou Is this fixed now?

**Comment by micbou** [comment]
Yes, thanks.
