### ISSUE TITLE
Missing whitespace in completion menu

### ISSUE THREAD

**Issue by Valloric** [abingham/emacs-ycmd#354]
![bug](https://cloud.githubusercontent.com/assets/919444/18610888/6a6e4270-7cdd-11e6-9efc-73f057712e2c.png)

Look at the first 4 entries in the completion menu. The name of the fields of the struct are right next to the type of the field, without any whitespace in between. Kinda hard to read.

In case the screenshot is not enough to figure out the root cause of the issue, you can repro like so:

1. Set up ycmd with `./install --racer-completer` so that it has Rust support.
2. Open [this file](https://github.com/Valloric/nailgun/blob/master/base/mod.rs) (after cloning the repo) and scroll to line 100. Type `node.` above it. That will produce the above picture.

**Comment by ptrv** [comment]
I tried to reproduce the error, however I can't get rust completion to work:
I have this error:

```
2016-09-18 00:23:40,743 - INFO - Starting new HTTP connection (1): 127.0.0.1
2016-09-18 00:23:40,746 - DEBUG - "POST /list_completions HTTP/1.1" 500 0
2016-09-18 00:23:40,747 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/home/peter/src/ycmd/ycmd/../ycmd/handlers.py", line 100, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/peter/src/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/peter/src/ycmd/ycmd/../ycmd/completers/completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/peter/src/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 242, in ComputeCandidatesInner
    completions = self._FetchCompletions( request_data )
  File "/home/peter/src/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 260, in _FetchCompletions
    return self._GetResponse( '/list_completions', request_data )
  File "/home/peter/src/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 176, in _GetResponse
    response.raise_for_status()
  File "/home/peter/src/ycmd/third_party/requests/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:60527/list_completions
```

Any ideas?

**Comment by Valloric** [comment]
That looks like we need a better error message somewhere. Seems like a 500 response from racerd. @jwilm Thoughts? The debugging experience here could be better.

@ptrv I think you'll need to set up the [rust source path var](https://github.com/Valloric/YouCompleteMe#rust-semantic-completion).

**Comment by Valloric** [comment]
For reference, [here's how I set up emacs-ycmd](https://github.com/Valloric/dotfiles/blob/master/emacs/spacemacs.el#L519).

**Comment by ptrv** [comment]
I am getting these errors with having set up the rust source path var.

The error log:

```
ERROR:iron::iron: Error handling:
Request {
    url: Url { generic_url: "http://127.0.0.1:43475/list_completions" }
    method: Post
    remote_addr: V4(127.0.0.1:39470)
    local_addr: V4(127.0.0.1:43475)
}
Error was: Error { repr: Custom(Custom { kind: Other, error: NotSupported }) }
```

**Comment by jwilm** [comment]
There's a bug in one of racerd's dependencies where it refuses to cooperate for certain terminals (or lack of terminal). Really need to publish an update for that...

**Comment by jwilm** [comment]
I just pushed a branch to `racerd` called `without-logger` which should make that error go away. A little more work needs to be done to publish a new version (actually want some form of logging), but this should allow you to get some completions @ptrv.

**Comment by ptrv** [comment]
@jwilm Thanks for the `without-logger` branch. I checked it out and was able to get completions and reproduce the issue mentioned by @Valloric.
