### ISSUE TITLE
Ycmd server timeout

### ISSUE THREAD

**Issue by moyotar** [abingham/emacs-ycmd#358]
My config.

```
(require 'ycmd)
(add-hook 'after-init-hook #'global-ycmd-mode)
(setq ycmd-toggle-force-semantic-completion t)
(set-variable 'ycmd-server-command
			  '("python" "D:/appdata/emacs/extraBin/ycmd/ycmd"))
(defun ycmd-setup-completion-at-point-function ()
  "Setup `completion-at-point-functions' for `ycmd-mode'."
  (add-hook 'completion-at-point-functions
            #'ycmd-complete-at-point nil :local))
(add-hook 'ycmd-mode #'ycmd-setup-completion-at-point-function)
(require 'company-ycmd)
(company-ycmd-setup)
(require 'flycheck-ycmd)
(flycheck-ycmd-setup)
(when (not (display-graphic-p))
  (setq flycheck-indication-mode nil))
(require 'ycmd-eldoc)
(add-hook 'ycmd-mode-hook 'ycmd-eldoc-setup)
(setq request-message-level -1)
```

init output.

File mode specification error: (error "ERROR: Ycmd server timeout")
You should have a section marked ";;; Commentary:"
The first line should be of the form: ";;; package --- Summary"
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://127.0.0.1:53841/shutdown. [2 times]
REQUEST [error] Error (error) while connecting to http://127.0.0.1:53841/ready. [5 times]
Ycmd server killed
ycmd--wait-until-server-ready: ERROR: Ycmd server timeout

**Comment by Congee** [comment]
HI, can you please tell me how to get those init output. My *Message* only outputs "server killed; timeout", not helpful at all.

**Comment by moyotar** [comment]
@Congee Hi. I got this from `*Messages*`.

**Comment by Congee** [comment]
@moyotar Thank you. It's weid that my *Message* doesn't show anything about this. Had to debug the emacs-ycmd source code.
