### ISSUE TITLE
Why can't it complete anything in a .cpp file?

### ISSUE THREAD

**Issue by moyotar** [abingham/emacs-ycmd#360]
This was the server output when opening the .cpp file.

>
 2016-09-30 11:41:09,683 - DEBUG - No global extra conf, not calling method YcmCorePreload
serving on http://127.0.0.1:51532
2016-09-30 11:41:09,828 - INFO - Received ready request
2016-09-30 11:41:09,960 - INFO - Received ready request
2016-09-30 11:41:10,075 - INFO - Received ready request
2016-09-30 11:41:10,190 - INFO - Received ready request
2016-09-30 11:41:10,299 - INFO - Received ready request
2016-09-30 11:41:10,408 - INFO - Received ready request
2016-09-30 11:41:10,520 - INFO - Received ready request
2016-09-30 11:41:10,630 - INFO - Received ready request
2016-09-30 11:41:10,740 - INFO - Received ready request
2016-09-30 11:41:10,861 - INFO - Received ready request
2016-09-30 11:41:10,974 - INFO - Received ready request
2016-09-30 11:41:11,096 - INFO - Received ready request
2016-09-30 11:41:11,207 - INFO - Received ready request
2016-09-30 11:41:11,331 - INFO - Received ready request
2016-09-30 11:41:11,444 - INFO - Received ready request
2016-09-30 11:41:11,553 - INFO - Received ready request
2016-09-30 11:41:11,664 - INFO - Received ready request
2016-09-30 11:41:11,775 - INFO - Received ready request
2016-09-30 11:41:11,894 - INFO - Received ready request
2016-09-30 11:41:12,006 - INFO - Received ready request
2016-09-30 11:41:12,119 - INFO - Received ready request
2016-09-30 11:41:12,230 - INFO - Received ready request
2016-09-30 11:41:12,341 - INFO - Received shutdown request

This is my all ycmd config.
```
(require 'ycmd)
(add-hook 'after-init-hook #'global-ycmd-mode)
(setq ycmd-toggle-force-semantic-completion nil)
(set-variable 'ycmd-server-command
			  '("D:/appdata/emacs/extraBin/Python27/python.exe" "-u" "D:/appdata/emacs/extraBin/ycmd/ycmd"))
(defun ycmd-setup-completion-at-point-function ()
  "Setup `completion-at-point-functions' for `ycmd-mode'."
  (add-hook 'completion-at-point-functions
            #'ycmd-complete-at-point nil :local))
(add-hook 'ycmd-mode #'ycmd-setup-completion-at-point-function)
(set-variable 'ycmd-global-config "D:/appdata/emacs/extraBin/ycmd/cpp/ycmd/.ycm_extra_conf.py")
(set-variable 'ycmd-extra-conf-whitelist '("E:/*"))
(require 'company-ycmd)
(company-ycmd-setup)
(require 'flycheck-ycmd)
(flycheck-ycmd-setup)
(when (not (display-graphic-p))
  (setq flycheck-indication-mode nil))
(require 'ycmd-eldoc)
(add-hook 'ycmd-mode-hook 'ycmd-eldoc-setup)
(setq request-message-level -1)
(provide 'ycmd-config)
```

And this is .ycm_extra_conf.py which is under E:/.  The difference with ycmd's own  .ycm_extra_conf.py  is  shown.

flags = [   
    '-std=c++11',   
    '-stdlib=libc++',   
    '-Wno-deprecated-declarations',   
    '-Wno-disabled-macro-expansion',   
    '-Wno-float-equal',   
    '-Wno-c++98-compat',   
    '-Wno-c++98-compat-pedantic',   
    '-Wno-global-constructors',   
    '-Wno-exit-time-destructors',   
    '-Wno-missing-prototypes',   
    '-Wno-padded',   
    '-x',   
    'c++',   
    '-I',   
    '.',   
    '-isystem',  
    'd:/appdata/emacs/extraBin/LLVM/include/clang-c',  
    '-isystem',  
    'd:/appdata/emacs/extraBin/LLVM/include/llvm-c',  
    '-isystem',  
    'D:/appdata/Microsoft Visual Studio 10.0/VC/include',  
]   

    # try:
    # final_flags.remove( '-stdlib=libc++' )
    # except ValueError:
    # pass

@abingham

**Comment by abingham** [comment]
If you put your cursor at some place that could be completed and run `M-x ycmd-display-completions`, do you get any results?

**Comment by moyotar** [comment]
After I typed "del" and ran `M-x` `ycmd-display-completions`, I got this.

> 
((completion_start_column . 2)
 (completions .
			  [((extra_menu_info . "[ID]")
				(insertion_text . "delete"))])
 (errors .
		 []))

**Comment by abingham** [comment]
It looks like the basic plumbing is working, so you must have a problem in how you've configured company or something.

A few things:
1. As I mentioned before, `(setq ycmd-toggle-force-semantic-completion nil)` is incorrect. That's a function. You're probably thinking about `ycmd-force-semantic-completion`, not the toggle function.
2. You don't need the `ycmd-setup-completion-at-point-function` stuff if you're going to use company (which it looks like you're trying to do)
3. If you're going to use company, have you configured it properly? See [the company-mode documentation](http://company-mode.github.io/) for details.

**Comment by moyotar** [comment]
My config was modified as  your suggestion. As for company, it can work in a .py file with ycmd. So I think it's not in company. Once again, I got this after typing "ret" which expected "return". 

> 
((completion_start_column . 2)
 (completions .
			  [])
 (errors .
		 []))

**Comment by abingham** [comment]
> What's more, the python.exe is easily crashed.
That's a pretty broad statement. Can you post some output?

**Comment by moyotar** [comment]
I  found nothing about why python.exe was crashed in ycmd-server. But I found something may caused this from emacs's *Messages* buffer.

> 
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://127.0.0.1:56880/shutdown. [2 times]
Ycmd server killed
File mode specification error: (error "ERROR: Ycmd server timeout")
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://127.0.0.1:56949/shutdown. [2 times]
Ycmd server killed
ycmd--wait-until-server-ready: ERROR: Ycmd server timeout
Mark set [2 times]
Auto-saving...done
Undo!
Mark set
Saving file e:/download/P2P-master/P2P-master/P2PDemo/P2PClient/Client.cpp...
Wrote e:/download/P2P-master/P2P-master/P2PDemo/P2PClient/Client.cpp
Quit [3 times]
Ycmd server error: ycm_core library compiled for Python 2 but loaded in Python 3.
REQUEST [error] Error (error) while connecting to http://127.0.0.1:57089/event_notification.
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://127.0.0.1:63255/shutdown. [2 times]
Ycmd server killed
ycmd--wait-until-server-ready: ERROR: Ycmd server timeout

**Comment by abingham** [comment]
This is probably the relevant part of the output:
```
Ycmd server error: ycm_core library compiled for Python 2 but loaded in Python 3.
```
See the [ycmd documentation](https://github.com/Valloric/ycmd#exit-codes) for more information.

This seems strange based on your config, though. I assume that the 'python.exe' in D:/appdata/emacs/extraBin/Python27/python.exe is actually python2.7, but ycmd seems to think it's being loaded in python3. I guess you should see if you can sort this out.

**Comment by moyotar** [comment]
I agree. I'm troubled with why ycmd thought it was loaded in python3. There's only pyhon2.7 in my machine.

**Comment by abingham** [comment]
You might open an issue with ycmd to get that sorted out.
