### ISSUE TITLE
ycmd-get-parent doesn't show the return type of function in C

### ISSUE THREAD

**Issue by zijianyue** [abingham/emacs-ycmd#363]
e.g. : a function like below
int func(int a, short b) 
ycmd-get-parent will show func(int, short).
Wish to improve that :)

**Comment by ptrv** [comment]
We show what `ycmd` server is returning. In your case it's just `func(int, short)`. We cannot do much about it on `emacs-ycmd` side.

You should report this in `ycmd` project.
