### ISSUE TITLE
Error in company-ycmd.el.

### ISSUE THREAD

**Issue by moyotar** [abingham/emacs-ycmd#364]
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "f")
  require(f)
  eval-buffer(#<buffer  *load*-665707> nil "d:/Program Files/emacs-config/.emacs.d/el-get/emacs-ycmd/company-ycmd.el" nil t)  ; Reading at buffer position 2320
  load-with-code-conversion("d:/Program Files/emacs-config/.emacs.d/el-get/emacs-ycmd/company-ycmd.el" "d:/Program Files/emacs-config/.emacs.d/el-get/emacs-ycmd/company-ycmd.el" nil t)
  require(company-ycmd)

**Comment by ptrv** [comment]
The package `f` is missing. You need to install it. It looks like el-get is not installing dependencies properly

**Comment by moyotar** [comment]
Awesome thanks!
