### ISSUE TITLE
Ycmd server timeout

### ISSUE THREAD

**Issue by damienrg** [abingham/emacs-ycmd#365]
Hi,

There are a lot of issues mentioning 'Ycmd server timeout' but none mention this problem.
After digging it seems that the issue is linked to ~/.ICEauthority. If I remove the file (or use a different HOME to launch emacs) there is no problem.
I do not know how to go further so it would be great if someone could help me.

The different logs:
*ycmd-server*:

> 2016-10-13 09:07:32,930 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
> serving on http://127.0.0.1:33882
> 2016-10-13 09:07:32,956 - INFO - Received ready request
> ...
> 2016-10-13 09:07:35,729 - INFO - Received ready request
> 2016-10-13 09:07:35,739 - INFO - Received shutdown request

*Messages*:

> REQUEST [debug] REQUEST
> REQUEST [debug] Run: curl --silent --include --location --compressed --cookie /home/dam/.emacs.d/request/curl-cookie-jar --cookie-jar /home/dam/.emacs.d/request/curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --data-binary @- --request GET --header Content-Type: application/json --header X-Ycm-Hmac: 0MXPg8hK6a/aVjsfIPXlsRWW+HDSdsIzkfmjbHysxTw= http://127.0.0.1:33882/ready?subserver=cpp
> ...
> REQUEST [debug] REQUEST
> REQUEST [debug] Run: curl --silent --include --location --compressed --cookie /home/dam/.emacs.d/request/curl-cookie-jar --cookie-jar /home/dam/.emacs.d/request/curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective "%{url_effective}") --data-binary @- --request GET --header Content-Type: application/json --header X-Ycm-Hmac: 0MXPg8hK6a/aVjsfIPXlsRWW+HDSdsIzkfmjbHysxTw= http://127.0.0.1:33882/ready?subserver=cpp
> REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
> REQUEST [error] Error (timeout) while connecting to http://127.0.0.1:33882/shutdown. [2 times]
> REQUEST [error] Error (error) while connecting to http://127.0.0.1:33882/ready. [22 times]
> File mode specification error: (error ERROR: Ycmd server timeout)

**Comment by ptrv** [comment]
Does this happen when you set `request-backend` to `'url-retrieve`?

**Comment by damienrg** [comment]
No, I do not have the problem using url-retrieve just the following message in \*Messages\*:

> Making url-show-status local to  *http 127.0.0.1:43278* while let-bound!

**Comment by ptrv** [comment]
You can ignore that message.

**Comment by damienrg** [comment]
Ok, do you have any hint on how I could find the problem with curl as request-backend?

**Comment by ptrv** [comment]
@damienrg Sorry for my late response. Unfortunately I don't have any suggestions how to find the problem because I don't even know how to reproduce the issue and what exactly is happening here.
