### ISSUE TITLE
Waiting for ycmd to start...

### ISSUE THREAD

**Issue by r4nt** [abingham/emacs-ycmd#369]
First:
Using request with curl (does not happen with url-retrieve), if ycmd takes a while to start (on my machine, roughly 3 seconds), we run out of file descriptors, after which point ycmd busy loops and emacs never starts.

There are a couple of questions here:
- should emacs-ycmd really wait for ycmd to start?
- I have no idea whether the curl pipe file descriptor leak problem is in emacs-ycmd or request, and my emacs-foo is not good enough to contribute a nice repro :(

**Comment by ptrv** [comment]
@r4nt Are you on the latest version of `emacs-ycmd`?

**Comment by ptrv** [comment]
There should be no requests until `ycmd` server is fully up and able to receive request. This was changed quite recently.

**Comment by r4nt** [comment]
I just tested with the current commit. Note that the wait-for-server is what is hanging.

**Comment by ptrv** [comment]
@r4nt Do you mean the function `ycmd--wait-until-server-ready` is hanging?

I tried to repro by adding a 3 seconds sleep to `YcmCorePreload`. In that case `ycmd-startup-timeout` needs to be set to more than 3 seconds which is the default. But I have no issues.

IMHO `emacs-ycmd` should wait for `ycmd` to start because only if the server is up and running you can send file parse or completion requests or other queries.

**Comment by r4nt** [comment]
@ptrv - correct, I mean ycmd--wait-until-server-ready. Are you using curl for request or url-retrieve?

I'm also not opposed to emacs-ycmd waiting, just that that waiting blocks emacs startup :)

**Comment by ptrv** [comment]
Yes, I am using `curl` as backend.

Do you have have `desktop-save-mode` enabled? Do you restore `ycmd-mode` enabled buffers when you start Emacs?

**Comment by r4nt** [comment]
Ah, this only happens when I start emacs with a C++ file (/me headdesks). I assume starting the mode in the background is not an option... ?

**Comment by phst** [comment]
FYI, here's a simple way to trigger the issue: Create a fake server `/tmp/ycmd.sh`:

```shell
#!/bin/bash
sleep 20
nc -v -l -p 9999
```

Then run

```el
(with-temp-buffer
  (let ((ycmd-server-command '("/tmp/ycmd.sh"))
        (ycmd-server-port 9999)
        (ycmd-startup-timeout 15))
    (ycmd-close)
    (ycmd-mode)))
```

and Emacs will hang (i.e. not react to input events) while the 'server' is starting.

**Comment by phst** [comment]
Better example. With `/tmp/ycmd.sh` as above, run in the `emacs-ycmd` directory

```shell
$ make && ../Emacs/src/emacs -Q -L . -eval '(progn (setq package-user-dir ".cask/25.1.1/elpa") (package-initialize) (require (quote ycmd)) (add-hook (quote c++-mode-hook) (quote ycmd-mode)) (set-variable (quote ycmd-server-command) (quote ("/tmp/ycmd.sh"))) (set-variable (quote ycmd-startup-timeout) 20))' /tmp/a.cc
```

It doesn't matter whether /tmp/a.cc actually exists. On the emacs-25 branch this crashes (due to an Emacs bug already fixed in master), on the master branch Emacs hangs and you'll get the error in *Messages*: File mode specification error: (file-error Creating pipe Too many open files)

The crash and the file error are a symptom of the leaking curl processes/file descriptors.

**Comment by phst** [comment]
If you set `request-backend` to `url-retrieve`, the FD leak is gone (to be expected), but the hangs are still there. I don't think Emacs should ever hang when the YCMD server is starting; rather, ycmd should wait asynchronously for the server to start. It's better to have a working Emacs temporarily without completion than a frozen Emacs.

**Comment by ptrv** [comment]
Waiting for the server (and blocking) to start was always there, this is nothing new. But I agree that it would be better if the YCMD server would start asynchronously and not blocking Emacs.

I'll look into this and try to find a way to start the server in a non-blocking manner.

**Comment by phst** [comment]
Thanks! Yes, the same issue happens with old versions of emacs-ycmd.

**Comment by r4nt** [comment]
@ptrv - do you know whether the "too many open files" problem is a ycmd or request.el problem?

**Comment by ptrv** [comment]
@r4nt I don't know exactly. I need to check the repro mentioned above to get an idea about it. But if this is not happening with `url-retrieve` I would think it is more an issue how the `curl` process is handled by `request.el`. But this is just guessing.

@r4nt @phst I have an experimental branch with async server start here: https://github.com/ptrv/emacs-ycmd/tree/async-server-start

Maybe you could try and tell me what you think.

**Comment by r4nt** [comment]
@d0k for testing :)

**Comment by phst** [comment]
I didn't test it thoroughly, but initial testing with the command from https://github.com/abingham/emacs-ycmd/issues/369#issuecomment-255807929 indicates that the hangs are indeed gone. Thanks!
