### ISSUE TITLE
Can't get c++ semantic completion.

### ISSUE THREAD

**Issue by moyotar** [abingham/emacs-ycmd#370]
@abingham @ptrv
My flags in `.ycm_extra_conf.py`.

> flags = [
> '-Wall',
> '-Wextra',
> '-Werror',
> '-fexceptions',
> '-DNDEBUG',
> '-std=c++11',
> '-x',
> 'c++',
> '-isystem',
> 'd:/appdata/Microsoft Visual Studio 10.0/VC/include',
> ]

I put it  in `E:\download\P2P-master\P2P-master\P2PDemo`.
And my test project is in `E:\download\P2P-master\P2P-master\P2PDemo\P2PClient`.

In my init-file.

```
(set-variable 'ycmd-global-config
              "D:/appdata/emacs/extraBin/ycmd/cpp/ycmd/.ycm_extra_conf.py")
(set-variable 'ycmd-extra-conf-whitelist
              '("e:/*"))
(setq ycmd-extra-conf-handler 'load)
```

In a cpp file of this project, in which I included `stdio.h`, I tried to type `sca` and expected `scanf`, but it failed.
There are something different in c file. I created `test.c` in this project and tested. As you see in the screenshot.
![image](https://cloud.githubusercontent.com/assets/22092607/19680279/a6400622-9ad7-11e6-9094-cf0ee597bc5f.png)

I was happy! I used `sca` to test in this file soonly. Unfortunately, I failed again. Back to the cpp file, I used `vector` to test once more and get many `macro` completion instead of its member function.
![image](https://cloud.githubusercontent.com/assets/22092607/19680516/8f938574-9ad8-11e6-860d-010e5348e997.png)

And this maybe helpful.
![image](https://cloud.githubusercontent.com/assets/22092607/19680840/bdf951e0-9ad9-11e6-87a8-432f02824c4a.png)

**Comment by abingham** [comment]
If you enter "sca" and then run `ycmd-display-completions`, does this show "scanf" in the results?

**Comment by moyotar** [comment]
> ((completion_start_column . 2)
>  (completions .
> 			  [])
>  (errors .
> 		 []))

**Comment by abingham** [comment]
Which compiler are you using?

**Comment by moyotar** [comment]
There are `clang` and `clang++`. I don't know which one that `ycmd` use.

**Comment by abingham** [comment]
You might check [this issue with ycmd](https://github.com/Valloric/YouCompleteMe#completion-doesnt-work-with-the-c-standard-library-headers).
