### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by ptrv** [abingham/emacs-ycmd#386]
I think we should release a new version.

The last release 0.9 is from January 2015 and it is up on MELPA stable.

@abingham I drafted a release locally. If you don't object I push the changes and make a release here on github.

@abingham Or should we even release 1.0?

**Comment by abingham** [comment]
I think a new release is definitely in order. Unless you have any API changes you plan to make, then let's go with 1.0!

**Comment by ptrv** [comment]
Ok, I'll release 1.0. Cool!
