### ISSUE TITLE
latest emacs-request version does not work with files that contain Unicode characters 

### ISSUE THREAD

**Issue by liugang** [abingham/emacs-ycmd#387]
`request.el` package is upgrade to latest version, emacs-ycmd not work with files contains Unicode characters, it always prompt *Waring* buffer, to ask you "Select coding system (default raw-text):

```shell
git clone https://github.com/abingham/emacs-ycmd.git
cd emacs-ycmd
```
add unicode code to test/resources/test.cpp 

```diff
diff --git a/test/resources/test.cpp b/test/resources/test.cpp
index 9d23f01..14811de 100644
--- a/test/resources/test.cpp
+++ b/test/resources/test.cpp
@@ -6,6 +6,6 @@ public:
 int main(int, char**) {
     Llama l;
     l.
-
+// 你好
     return 0;
 }
```

```shell
make test
```

```
   passed  45/61  ycmd-test-fixit-cpp-notes
   passed  46/61  ycmd-test-fixit-cpp-replace
   passed  47/61  ycmd-test-fixit-same-location-false
   passed  48/61  ycmd-test-fixit-same-location-true
Select coding system (default raw-text): 
```

I have traced the issue, it was caused by commit tkf/emacs-request@6e039bf

Should  emacs-ycmd do something to fix this issue?
or it is a bug of emacs-request?

**Comment by ptrv** [comment]
If you could trace down the issue in `request.el` please file a bug there first. And then we see if we need to do something in `emacs-ycmd`

**Comment by ptrv** [comment]
This issue is only when using `curl` as `request-backend`. Setting it to `url-retrieve` should fix the issue.

I have a PR in `request.el` to fix the issue: https://github.com/tkf/emacs-request/issues/58

**Comment by ptrv** [comment]
https://github.com/tkf/emacs-request/pull/58 has been merged.

**Comment by liugang** [comment]
Thanks!
