### ISSUE TITLE
Indicate parsing progress

### ISSUE THREAD

**Issue by beojan** [abingham/emacs-ycmd#388]
Is there any way to indicate progress in parsing the file? At least in spacemacs, something in the powerline would be ideal.

**Comment by ptrv** [comment]
There is already an indication for parsing in progress. A small star next to the ycmd mode name in the mode-line.

**Comment by beojan** [comment]
I see. Could it be made more obvious (some form of coloured indicator, rather than a small star)?

**Comment by ptrv** [comment]
IMHO it is pretty obvious.

I am not sure whether you can have a different color for single characters in the mode-line.

You could develop an external addon package for `emacs-ycmd` like the [flycheck-color-mode-line](https://github.com/flycheck/flycheck-color-mode-line) addon package for `flycheck`.

**Comment by ptrv** [comment]
Closing because it's out of the scope of this package but could be added to the `contrib` folder in this repo.
