### ISSUE TITLE
buffer is using the wrong compilation flags.

### ISSUE THREAD

**Issue by amosbird** [abingham/emacs-ycmd#389]
I'm using `Bear` to generate `compile_commands.json` in a Makefile project. When creating new `cc` files, emacs-ycmd keeps using the old compilation flags. I have to restart emacs to make it right.

i've tried `ycmd-clear-compilation-flag-cache (C-c Y C)`, `ycmd-restart-semantic-server (C-c Y O)` and `ycmd-mode` toggling. None of them works.

```
Ycmd debug information for buffer 450.cc in c++-mode:


"Server has Clang support compiled in: True
Clang version: clang version 3.9.0 (tags/RELEASE_390/final)
C-family completer debug information:
  Configuration file found and loaded
  Configuration path: /home/amos/.emacs.d/layers/+tools/ycmd/global_conf.py
  Flags: ['c++', '-x', 'c++', '-g', '-O0', '-std=c++11', '432.cc', '-resource-dir=/home/amos/ycmd/ycmd/../clang_includes', '-fspell-checking']"


Server is running at: 127.0.0.1:43842

Ycmd Mode is enabled

--------------------

Ycmd version:   1.1snapshot (package: 20161128.358)
Emacs version:  25.1.1
System:         x86_64-unknown-linux-gnu
Window system:  x
```

**Comment by ptrv** [comment]
This issue depends on how you read the `compile_commands.json` file in your `global_conf.py`. The `global_conf.py` get read once when you start the server and probably you read the `compile_commands.json` only when reading the config file. If you add a new file (and changing the `compile_commands.json) you have to start the server because of this.

**Comment by amosbird** [comment]
hmm, doesn't `ycmd-restart-semantic-server (C-c Y O)` suffice?

**Comment by ptrv** [comment]
> doesn't `ycmd-restart-semantic-server (C-c Y O)` suffice?

No because that does not trigger a re-read of the config file.

**Comment by amosbird** [comment]
so what should I do? Is there a better way instead of restarting ycmd? Should we have a command that re-read the config file?

**Comment by abingham** [comment]
@amosbird Running `ycmd-open` will kill any running server and start a new one. I think that's the closest we've got to a command for re-reading the config file. Does that smooth things out for you a bit? 

You might be able to use [`file-notify-add-watch`](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Notifications.html) to monitor your commands file and restart the server when it changes. That might be too disruptive in practice, but it might be worth trying if you're changing that file a lot.

**Comment by amosbird** [comment]
@abingham no, `ycmd-open` doesn't help here.

**Comment by abingham** [comment]
That's curious. In the `*ycmd-server*` buffer, do you see the server being stopped and started when you run `ycmd-open`? That's what you should see, and that should (as far as I know) result in a complete re-rereading of your config.

If you don't see the server being restart on `ycmd-open`, perhaps try `ycmd-close` followed by `ycmd-open`. That should not technically be necessary, but perhaps we're facing down a new bug of some sort.

**Comment by ptrv** [comment]
I am now confused. @amosbird I thought restarting the server helps.

If you want to achieve that a new `compile_commands.json` after adding a file is taken into account you have to add the logic into the `global_conf.py` to detect if the file has been change and then re-read the json file. That is also what the authors of upstream `ycmd` suggested. The proble here is just the implementation og the global config.

I am always facing the same issue when adding a new file to a project for which I use a `compile_commands.json` and I just restart the server. This was never annoying enought to me that I need to re-write my `.ycm_extra_cong.py`

**Comment by amosbird** [comment]
@abingham hmm. `ycmd-open` resets the `*ycmd-serever*` buffer with 
```
2016-12-07 16:57:55,660 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
serving on http://127.0.0.1:42147
```

I'm using the default configuration that spacemacs gives.

**Comment by ptrv** [comment]
@amosbird Looks fine. The server restarted properly.

I quickly looked at the `global_conf.py` from spacemacs and it checks and loads the `compile_command.json` on every call for `FlagsForFile`. I'll have a more thorough look at this and I will try to reproduce this.

However this seems not a general issues with `emacs-ycmd`, more configuration thing.

**Comment by deb0ch** [comment]
I wrote the `global_conf.py` that Spacemacs currently uses, just let me know if I can be of any help - and I'm always interested to know if there was something wrong with my code :smile_cat:

**Comment by abingham** [comment]
Can this be closed?

**Comment by amosbird** [comment]
Yeah, it works fine now. Thanks!

**Comment by abingham** [comment]
Awesome, thanks!
