### ISSUE TITLE
Forced semantic, manual, and include files

### ISSUE THREAD

**Issue by quicknir** [abingham/emacs-ycmd#390]
I work in a fairly large C++ project. ycmd is awesome and works very well, but it's just not nearly fast enough to give a good experience on as you type completion. So I'm using a trivial completer for as you type completions (dabbrev-code from company). I bind a manual key to trigger ycmd:

``` elisp
  (defun ycm ()
    (interactive)
    (company-abort)
    (setq company-backend 'company-ycmd)
    (company-manual-begin))
  (global-set-key (kbd "<C-tab>") 'ycm)
```

So far, great. However, there are two annoying issues, both related to #includes. I depend on ycmd for excellent #include completion. However, with this setup, I have to repeatedly hit C-tab after every directory. Is there not a way for selecting a completion in the ycmd include completer, to automatically start completion within that directory?

The second annoying issue is related to forcing ycmd to only offer semantic completions. Since I get identifier based completions as I type, when I hit auto complete I want semantic completions. Without this set, in the global namespace, I get identifier based completions. So I set this. However, if this is set, then ycmd can't really offer include completions at all. As soon as I start typing new #includes it starts going crazy reparsing the entire file from scratch, which takes 10+ seconds. It seems like the same variable (force semantic completion) is controlling both ycmd's completions in the global namespace, and how it handles include completion. Maybe it is possible to have ycmd offer semantic completions at global scope, but still not go crazy when completing includes?

I should maybe add: I've had perf issues that I think may be related to forcing semantic completion. But these issues kick in even when i don't trigger completion, and even though ycmd is not on the company backends list. Anyone else see this?

Cheers.

**Comment by ptrv** [comment]
Hi,

Include completion is not part of the semantic completion. If you are trying to complete an include with force semantic enabled it won't work. Enabling force semantic completion always is not really recommended. Why don't you use also the identifier completer from ycmd?

I have also a function that always triggers semantic completion but my "as you type" completion (aka company idle completion) doesn't force semantic completion but still get it after a semantic trigger. In that function I just let-bind `ycmd-force-semantic-completion` like this:

```emacs-lisp
(defun ycm (arg)
    (interactive "P")
    (let ((ycmd-force-semantic-completion (not arg)))
      (company-cancel)
      (company-complete)))
```

So, if you want to have semantic completion with a shortcut but not when completing an include you could just modify your function without setting `ycmd-force-semantic-completion` globally:

```emacs-lisp
(defun ycm ()
  (interactive)
  (company-abort)
  (setq company-backend 'company-ycmd)
  (let ((ycmd-force-semantic-completion (not (company-ycmd--in-include))))
    (company-manual-begin)))
```

Hope this helps.

Regarding your performance issue you have to provide more information in order that we can say more. When does it happen? Whan you complete or in a different situation?

**Comment by quicknir** [comment]
@ptrv I basically have two options: 1) have ycmd trigger as I type, or 2) make ycmd manual and use a separate identifier based completer. If I make it trigger as I type, then the ycmd identifier completion is fine, but then as soon as I hit `.` or `->` or `::`, it launches into semantic completion. My project is large and there's a noticeable delay, and sometimes I don't need the help because I know exactly what I'm typing. On the flipside, if I do 2), then even if I follow your suggestion and disable forced semantic completion, I will still need to keep re-hitting the key as I work with #includes for each directory. Is there any way to disable switching to semantic completion on ./->/:: ?

I'm happy to follow your suggestion, it seems like a good one, thanks! It will definitely help with both #includes and perf while still having unqualified semantic completion easily available.

The performance thing is hard to be more specific; it's just a general sluggishness that I observe with force semantic. One particular thing that I noticed is that company's other, completely unrelated completers are significantly slower. I use dabbrev-code I mostly mentioned on the off chance that it's a known issue since I can't provide enough systematic information. Does ycmd only do stuff when I complete? Is ycmd is actually preparing completions in the background based on cursor location before completion starts?

**Comment by quicknir** [comment]
@ptrv So there is actually a solution for this. Right now, emacs-ycmd hardcodes auto_trigger 1 on line 1891 of ycmd.el. If I manually set this to 0, this prevents semantic completion from triggering automatically. Despite the description in the docs, at least with company, ycmd continues to function as an identifier based completion engine. So, in this situation I can use ycmd as my first company backend, and have it trigger as I type, for identifiers & include files. Then turn on force-semantic on the fly in my ycm function. Can you introduce a variable for auto_trigger instead of hardcoding it? Or I can submit a PR, whatever you prefer.

**Comment by quicknir** [comment]
Actually, there needs to be a way to set this per language, maybe make it a buffer local variable? Not sure though...

**Comment by ptrv** [comment]
PR #391 adds a `defcustom` to be able to set `auto_trigger`. This variable does not make sense to set it as buffer local variable because the `auto_trigger` option is set once for the server at start. Setting this in a different buffer has no effect.

**Comment by quicknir** [comment]
@ptrv I see. So emacs-ycmd only ever opens one server? So currently there is no way to have auto_trigger say, on for python, but off for C++? Do you think I should try to raise this upstream and suggest making auto_trigger a per-language setting? This restriction seems artificial.

Thanks for your help!

**Comment by ptrv** [comment]
If the issue is important enough for you, raise it upstream :smile:

IMHO it's an edge case and your personal workflow thing. I personally never thought about using it this way (I also work on a fairly big c++ codebase at work). However, you can also solve it easily with `company-dabbrev` and the function I posted above. But if upstream adds your requested feature I am happy to integrate it in `emacs-ycmd`.

**Comment by quicknir** [comment]
Yes, that's a fair assessment, and it's a bit of a longshot. Maybe I won't bother raising it. In any case thank you very much for your help on this issue, and more broadly for gifting emacs-ycmd to the world. I use spacemacs + ycmd + rtags to have a really awesome C++ IDE setup and it would not be anywhere near as good without ycmd... so thanks!
