### ISSUE TITLE
complete_in_strings does not work in C code

### ISSUE THREAD

**Issue by zijianyue** [abingham/emacs-ycmd#392]
the default value of complete_in_strings  is 1 in default_settings.json of ycmd server, but it does not work in C code,  for I found company-capf rather than company-ycmd worked when completing in string.
e.g:  complete in a string in "abc "

**Comment by zijianyue** [comment]
no an issue ,but a limit in company-ycmd .The limit function is company-ycmd--prefix.

**Comment by ptrv** [comment]
The `default_settings.json` also consists of options which is not used in the server but in client code, like `complete_in_comments` or `complete_in_string`, which is confusing sometimes.

Should we make options for complete in strings or in comments?

/cc @abingham
