### ISSUE TITLE
Emacs freezes when inside large c++ project.

### ISSUE THREAD

**Issue by amosbird** [abingham/emacs-ycmd#399]
`C-g` resumes emacs, but after 5-10 seconds it freezes again. ` toggle-debug-on-error` is enabled, however backtrace is not printed. Disable `ycmd` mode and this problem is gone.

**Comment by ptrv** [comment]
Do you have `ycmd-eldoc` enabled?

**Comment by amosbird** [comment]
@ptrv um, how can I tell ? Here are all my minor modes, ![](https://ptpb.pw/XHc1.jpg)

**Comment by ptrv** [comment]
In a c++ file in that large project do: `M-x describe-variable RET eldoc-documentation-function RET` and post the value of that variable.

**Comment by amosbird** [comment]
The text output messes up the clipboard. Here is the picture output ![](https://ptpb.pw/t1FJ.jpg)

**Comment by ptrv** [comment]
Ok, `ycmd-eldoc` is enabled. It probably causes the freeze/hang because it does a synchronous ycmd request, which can take longer in a large c++ project. I recommend to disable it in `c++-mode`.

**Comment by amosbird** [comment]
Oh, what is the correct way to disable it?

**Comment by amosbird** [comment]
Ah, got it. `  (remove-hook 'ycmd-mode-hook 'ycmd-eldoc-setup)`
