### ISSUE TITLE
Ycmd crashes without any error messages.

### ISSUE THREAD

**Issue by nicber** [abingham/emacs-ycmd#401]
As it says in the title, I can't get ycmd to work on my projects.

Maybe these lines from the Messages buffer are relevant:
```
gui-get-primary-selection: No selection is available
Ycmd server killed
ERROR: Ycmd server timeout
```

An interesting fact is that it can be used if I restart it with ycmd-open.

I am using the latest version installed by Spacemacs.

**Comment by abingham** [comment]
I'm not sure why you might be seeing this, but it seems to be coming from [`select.el`](https://github.com/emacs-mirror/emacs/blob/master/lisp/select.el#L245). Can you use `stack-trace-on-error` or `debug-on-error` to see the context in which this is happening?

**Comment by nicber** [comment]
It seems to be unrelated.
It happens if I open the file by clicking on it in the home screen. If I press RET it doesn't show up.

**Comment by abingham** [comment]
So this happens when you start emacs and click on a file from the `*spacemacs*` buffer's "Recent Files" list?

What does the `*ycmd-server*` buffer show?

**Comment by nicber** [comment]
ycmd crashes no matter how I open the file. If I open it with the mouse the
GUI selection error appears.

The ycmd-server buffer is empty

Il 27/feb/2017 01:21 PM, "abingham" <notifications@github.com> ha scritto:

**Comment by abingham** [comment]
Hmmm...does `ycmd-show-debug-info` show anything that looks useful?

**Comment by nicber** [comment]
No debug info available from server

Server is not running

Ycmd Mode is enabled

--------------------

Ycmd version:   1.1snapshot (package: 20170114.445)
Emacs version:  25.1.1
System:         x86_64-w64-mingw32
Window system:  w32

**Comment by nicber** [comment]
I found a workaround: setting ycmd-startup-timeout to 10 seems to fix the problem.

**Comment by abingham** [comment]
OK, good, that was kind of thing I was going to suggest you look at next.
Can I go ahead and close this, or do you think there's more to do?

**Comment by nicber** [comment]
Maybe the timeout can be longer by default to avoid similar issues?

**Comment by abingham** [comment]
A longer timeout might be the right way to go, but I don't want to do that until/unless we get more reports of similar problems. Yours is the first that I know of.

What I have done, though, is added some text to the error message printed when a timeout occurs. Now is tells users that that they might need to increase the value of `ycmd-startup-timeout`. Thanks for working with us on this!
