### ISSUE TITLE
Using a proxy for http...

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abingham/emacs-ycmd#403]
Remember #234?  Looks like now we have yet another problem.  After upgrading to the latest, I get this:

```
Using a proxy for http...
deferred error : (error "$http_proxy/80 Name or service not known")
```

Just a minor point: why there is a space between `error` and `:` (looks bad)?

Anyway, seems like now `$http_proxy` and `$https_proxy` environment variables are checked somewhere.  We should guard against this too via the same or dedicated `defcustom`.

**Comment by ptrv** [comment]
Is this when using `curl` as request backend? Have you tried to unset those environment variables. Is this also when using `url-retrieve` as request backend?

What are you refering to with

> After upgrading to the latest

ymcd? or emacs-ycmd? or your OS?

There was no recent work in this area on emacs-ycmd side.

**Comment by Alexander-Shukaev** [comment]
Kindly want to apologize for the delay.  Will look into this as time permits.

**Comment by ptrv** [comment]
@Alexander-Shukaev Can you please check if #438 fixes this issue?

**Comment by Alexander-Shukaev** [comment]
@ptrv, you're the best! :+1:
