### ISSUE TITLE
No response to BufferVisit event and no prompt to load extra configuration.

### ISSUE THREAD

**Issue by naeloued** [abingham/emacs-ycmd#404]
Hi,

I've found that ymcd server fails to respond to BufferVisit event with specific C++ files (one example [here](http://hevc.kw.bbc.co.uk/git/w/jctvc-hm.git/blob_plain/HEAD:/source/App/TAppDecoder/decmain.cpp)).

However, there is no issue with the code sample below.  

```
 int main(int argc, char* argv[])
 {
   // dummy comment
   myObject.create();

   Double mydouble;
   clock_t start = clock();

   // call function
   myObject.func();

   // clean
   myObject.clean();

  return returnCode;
}
```
I'm using emacs 25.1.1, Fedora24,  ycmd-20170227.2341 and latest commit of ycmd master branch.

Looking at YCMD log, I've found that ycmd responds "nil" to BufferVisit event with code sample above. Then, emacs-ycmd sends a FileReadyToParse request. YCMD server throws UnknownExtraConf exception and emacs prompt to load the local extra configuration. Then, ycmd status is "parsed" and completion works correctly.

With this [file](http://hevc.kw.bbc.co.uk/git/w/jctvc-hm.git/blob_plain/HEAD:/source/App/TAppDecoder/decmain.cpp), ycmd status seems stuck on unparsed (ycmd? in mode line) value. It seems that "nil" response to BufferVisit event is never received or processed. As a result, there is no prompt for the extra conf and completion is not working.

I made my tests with both files in the same directory with this extra configuration file.

```
def FlagsForFile( filename, **kwargs ):
  return {
    'flags': [ '-x', 'c++', '-Wall', '-Wextra', '-Werror' ]
  }
```

Please let me know if this behavior is due to an error in my configuration files. I also tried to add the extra configuration in the whitelist but the bug still happens.

**Comment by ptrv** [comment]
I've tried out your example [file](http://hevc.kw.bbc.co.uk/git/w/jctvc-hm.git/blob_plain/HEAD:/source/App/TAppDecoder/decmain.cpp) and the extra configuration and ycmd everything worked fine. There is no includes in the extra configuration so ycmd won't find everything but semantic completion works for some types.

`BufferVisit` does not return anything, so `nil` is correct.

You have to provide some more information about you configuration and more exact reproduction steps since I can not find anything suspicious in your report.

Can you also post the server output?

**Comment by naeloued** [comment]
Thanks for trying to help me. I'll try to give you more details.

Here is my init.el:

```
;; Additional package repository
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
;;  (add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(package-initialize)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (flycheck-ycmd company-ycmd ycmd))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(when (require 'ycmd  nil 'no-error)
  (add-hook 'c++-mode-hook 'ycmd-mode)
  (add-hook 'c-mode-hook 'ycmd-mode)
  (set-variable 'ycmd-server-command '("python" "/home/ycmd/"))
  (set-variable 'ycmd-extra-conf-whitelist '("/home/bugreport")))

(when (require 'company-ycmd nil 'no-error)
  (company-ycmd-setup))

(when (require 'flycheck-ycmd nil 'no-error)
  (flycheck-ycmd-setup)
  (add-hook 'c-mode-hook 'flycheck-mode)
  (add-hook 'c++-mode-hook 'flycheck-mode)
  (when (not (display-graphic-p)) (setq flycheck-indication-mode nil)))
```

There is 3 files in /home/bugreport:
- The extra configuration file
- The decmain.cpp file.
- ok.cpp file which contains the code sample of my first comment.

I built ycmd (https://github.com/Valloric/ycmd/commit/dd33f885d2e3fd3daaa927b70c730b42215dd61f) using Python 2.7.13 

I open decmain.cpp using $ emacs decmain.cpp command line. Server output is:

```
2017-03-10 09:08:37,919 - DEBUG - No global extra conf, not calling method YcmCorePreload
serving on http://127.0.0.1:36715
2017-03-10 09:08:38,984 - INFO - Received event notification
2017-03-10 09:08:38,985 - DEBUG - Event name: BufferVisit
```
If ycmd content log is enabled before opening the file, the content log buffer contains only the HTTP REQUEST but HTTP RESPONSE is never received.

**Comment by naeloued** [comment]
The issue seems related to my proxy configuration. I am using CNTLM and have http_proxy environment variable set to localhost:3128.

When http_proxy is set, ycmd successfully parses ok.cpp file but not decmain.cpp.
When http_proxy is not set, ycmd successfully parses both files.

I added 127.0.0.1 in no_proxy env var and everything now works well. 
Maybe it is not a emacs-ycmd bug. Probably related to #403.

**Comment by Alexander-Shukaev** [comment]
It's unlikely `emacs-ycmd` bug.  Nevertheless, `emacs-ycmd` has to be resilient regardless of (broken) environment.  It must guard itself from unintentional and non-transparent usage of environment variables.

**Comment by ptrv** [comment]
@naeloued Can you please check if #438 fixes this issue?

**Comment by naeloued** [comment]
Thanks for fixing this issue. I just checked, it works now with or without no-proxy env. Thanks again.
