### ISSUE TITLE
Quickly delete unwanted arguments

### ISSUE THREAD

**Issue by amosbird** [abingham/emacs-ycmd#408]
I'm not sure if it is an issue of `emacs-ycmd`.  A completion of python's print function looks like this,
```
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
```
How can I quickly delete all the unneeded arguments? yasnippet supports `ctrl-d` to delete them one by one.

**Comment by abingham** [comment]
I think this is actually a question for company-mode. We provide company-mode with details about parameters, default, values, etc., and it manages the actual user interactions, completion, and so forth. You might check with them.

I'm going to close this, but by all means feel free to open it again if it does turn out to be an emacs-ycmd issue.

**Comment by ptrv** [comment]
I ran also into the issue that I wanted to remove unneeded arguments quickly. Haven't had time to look into.

Another idea is to not insert arguments which have a default value.
