### ISSUE TITLE
Possible breakage; ycmd-deferred:timeout

### ISSUE THREAD

**Issue by quicknir** [abingham/emacs-ycmd#425]
I updated all packages just a couple of days ago on my other machine and everything was working fine. Today, same setup on another machine and I'm getting the following error while trying to complete using company-ycmd:

Company: backend company-ycmd error "Invalid function: ycmd-deferred:timeout" with args (candidates )

I see that my ycmd is from 20170514, i..e yesterday, so I wonder if it is possible that a bug was just pushed? ycmd-flycheck continues to work fine so I'm pretty sure the file is getting parsed correctly.

**Comment by ptrv** [comment]
Which version is `company-ycmd`. Should also be 20170514.

**Comment by quicknir** [comment]
It is.

**Comment by ptrv** [comment]
which emacs version?

**Comment by quicknir** [comment]
25.1.1

**Comment by quicknir** [comment]
It is possible that something got corrupted, I could try to clear the cache and re-download.

**Comment by ptrv** [comment]
yes please, try to clear and re-download

**Comment by quicknir** [comment]
Strange, works now. My apologies I should have tried that before bothering you.

**Comment by ptrv** [comment]
Ok, I am glad it works again.

**Comment by drott** [comment]
I faced the same probably, and it started working after updating company-ycmd and ycmd, then removing all precompiled *ycmd*.elc files.
