### ISSUE TITLE
ERROR: Invalid function: ycmd-deferred:timeout

### ISSUE THREAD

**Issue by noxdafox** [abingham/emacs-ycmd#426]
Recent update of emacs-ycmd broke Company completion.

```
Company: An error occurred in auto-begin
Company: backend company-ycmd error "Invalid function: ycmd-deferred:timeout" with args (candidates reques)
```

To be sure, I updated ycmd code to its last revision as well. The issue is still present.

ycmd-server logs don't show anything suspicious.

**Comment by noxdafox** [comment]
I suspect this is the commit which broke: https://github.com/abingham/emacs-ycmd/commit/091a873899a64b0f7ba8730ff05c2e9db0e889d2

**Comment by ptrv** [comment]
@noxdafox Can you please try to remove you company-ycmd folder and reinstall?

See: https://github.com/abingham/emacs-ycmd/issues/425

**Comment by noxdafox** [comment]
That solved my problem but now it seems semantic completion behaves different (on Python).

Parameters are not expanded anymore.

**Comment by ptrv** [comment]
I think the problem is that `company-ycmd` and `ycmd` was outdated and `package.el` updated `company-ycmd` before `ycmd` and byte-compiled it with the not yet defined `ycmd-deferred:timeout` macro.

**Comment by noxdafox** [comment]
Yes it probably is the issue. Maybe converting ycmd-deferred to an actual function?
