### ISSUE TITLE
make ycmd use projectile root directory as current working directory

### ISSUE THREAD

**Issue by amosbird** [abingham/emacs-ycmd#430]
Hi, is there a way to make ycmd use projectile root directory as current working directory? This would ease manual crafting of ycmd flags with relative include search paths.

**Comment by abingham** [comment]
Did you figure out how to do what you wanted?

**Comment by amosbird** [comment]
@abingham well, I think adjusting ycmd_conf.py will do. That's not an emacs-ycmd issue though :smile:

**Comment by abingham** [comment]
Cool, I was thinking something like that might work. I'm glad you got it sorted!
