### ISSUE TITLE
doc: emacs-ycmd requires 127.0.0.1 to be in the NO_PROXY env variable

### ISSUE THREAD

**Issue by vmandela** [abingham/emacs-ycmd#437]
At work, emacs-ycmd did not work for me at all till today.  I would always see in the debug logs.

```
HTTP RESPONSE CONTENT

nil
```

After looking at https://github.com/abingham/emacs-ycmd/issues/404 , I added 127.0.0.1 to the NO_PROXY and no_proxy environment variables and was able to get emacs-ycmd to work. Please add this information regarding NO_PROXY and no_proxy variable setup to the documentation.

I did not face this issue with the YouCompleteMe vim plugin.

regards,
Venkat

**Comment by micbou** [comment]
emacs-ycmd could automatically set the `no_proxy` environment variable [like YCM does](https://github.com/Valloric/YouCompleteMe/blob/master/python/ycm/youcompleteme.py#L56-L70).

**Comment by ptrv** [comment]
I see. Thanks @micbou for the hint. Since we are getting this report from time to time I guess it would be a good idea to set the no proxe environment variable for the `ycmd` communication

**Comment by ptrv** [comment]
See #438 

The PR add the `no_proxy` variable to the envrionment to bypass proxies
