### ISSUE TITLE
Why the number of process such as marked in the pic will keep increasing and finally cause  an error.

### ISSUE THREAD

**Issue by moyotar** [abingham/emacs-ycmd#440]
![image](https://user-images.githubusercontent.com/22092607/28921456-9bfe2862-7888-11e7-95f7-dc81f0c71092.png)

**Comment by abingham** [comment]
Can you provide any more details? For example, do you know if the connections are from emacs to ycmd or from ycmd to one of its sub-servers?

**Comment by moyotar** [comment]
How to know this? Yesterday, when meeting this error, I tried to know more  about these connections but found nothing more.

**Comment by moyotar** [comment]
![image](https://user-images.githubusercontent.com/22092607/28951904-55315558-7900-11e7-8546-c83102fa0bcd.png)
Like this. The number of such connections will keep increasing.

**Comment by abingham** [comment]
What's your value for `request-backend`? One possibility is that request.el is using url.el (e.g. because you don't have curl installed), and whatever network connections it opens are not getting closed. This *might* be because of something emacs-ycmd is doing, but it seems unlikely since this is the first we're hearing about it.

**Comment by moyotar** [comment]
![image](https://user-images.githubusercontent.com/22092607/28970878-a9690740-795c-11e7-9a31-6de9f7bb2888.png)
Company: An error occurred in auto-begin
Company: backend (company-ycmd company-files company-keywords company-capf company-yasnippet) error "make client process failed: too many open files, :name, 127.0.0.1, :buffer, #<killed buffer>, :host, 127.0.0.1, :service, 51803, :nowait, nil" with args (candidates )
Error while checking syntax automatically: (file-error "Spawning child process" "resource temporarily unavailable") 
![image](https://user-images.githubusercontent.com/22092607/28969254-721340b8-7956-11e7-917d-71d4c7a6a057.png)

**Comment by abingham** [comment]
Yeah, I think this might be a bug in url.el. One way to verify this would be to use curl (the default backend for request.el) and see if this problem goes away.

You might also ask on stackoverflow if there are known problems with url.el. windows, and orphaned connections.

**Comment by ptrv** [comment]
I am using `url-retrieve` as backend on Mac and Linux and I don't have this problem.

@moyotar Which Emacs version do you use?

As @abingham pointed out this could also be a bug in `url.el`

**Comment by moyotar** [comment]
Sorry for taking a long time to reply.  @ptrv My Emacs version is 24.5.1 on windows 10. @abingham Ok, I will change the request backend to curl and report at once if this problem still exists.

**Comment by moyotar** [comment]
Similarly,  another error occurs.

![image](https://user-images.githubusercontent.com/22092607/29079964-277128de-7c91-11e7-8642-dc63da23e1cf.png)

> request curl    run      *request curl* --           curl --silent --include --location --compressed --cookie d:\Program Files\emacs-config\.emacs.d\request\curl-cookie-jar --cookie-jar d:\Program Files\emacs-config\.emacs.d\request\curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective %{url_effective}) --data-binary @- --request POST --header Content-Type: application/json --header X-Ycm-Hmac: rj5nWp8jQ+bLRmqCDOj5WW5KfCOnXKneHtGSLndfmvw= http://127.0.0.1:62709/completions

![image](https://user-images.githubusercontent.com/22092607/29079874-e89fea46-7c90-11e7-94c9-075984c46f7d.png)

**Comment by moyotar** [comment]
@abingham @ptrv No matter which backend I choose， It will cause too much process finally.
