### ISSUE TITLE
It really makes me very troubled. 

### ISSUE THREAD

**Issue by moyotar** [abingham/emacs-ycmd#442]
> OS:  win 10
> emacs version: GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570
> emacs-ycmd version: 1.3snapshot

With `ycmd` running a little time, I met similar error no matter which request backend I chose, `curl` or `url-retrieve`.  Now when meeting this error, I have to kill emacs and reopen it to make it serves normally.

And there are two issues reference for more info about error.

1. #440 
2. https://github.com/Valloric/ycmd/issues/619

**Comment by moyotar** [comment]
@abingham @ptrv Sorry for disturbing you. What's the reason  of this problem? `curl`, `url-retrieve` or `emacs-ycmd` ? Is there a way to solve it now?

**Comment by abingham** [comment]
I'm sorry, but I really don't know. I don't have a Windows machine on which
to test it, and as far as I know you're the only person experiencing this
problem. I really wish I could help, but I don't know what else I can do
right now.

For what it's worth, I suspect that this is not a problem specific to
emacs-ycmd (though we may be part of the problem somehow).

**Comment by moyotar** [comment]
![image](https://user-images.githubusercontent.com/22092607/29610006-7e1df248-882b-11e7-8d15-1d0c3fc25cb9.png)

Thanks! There's a new discovery that I can reproduce the error above with `curl` used. To more accurately, when I use `projectile-kill-buffers` to close current project(`python`), `ycmd `will be closed and buffer `*ycmd-server*` will be killed too. Then,  after I enter an other project(`python`) and restart `ycmd`, many connections as picture shows above will be produced quickly.

**Comment by moyotar** [comment]
Oh, if I close `ycmd` firstly before using `projectile-kill-buffers`, the error will not take place. I don't know these whether it's helpful.
