### ISSUE TITLE
How to generate tags file which can be recognized by ycmd using GNU GLOBAL?

### ISSUE THREAD

**Issue by moyotar** [abingham/emacs-ycmd#445]
Firstly, through looking up ycmd's varibles about tags, I set `ycmd-tag-files`  to `auto` and the `ycmd-default-tags-file-name` to `GTAGS`(I use `GNU GLOBAL` as tagging system). I found it doesn't work.
Secondly, by viewing the history  issue #150 , I realized it that tags file should be generated with `--fields=+l` option using `ctags`.  So, How to  generate tags file which can be recognized by ycmd using GNU GLOBAL? Additionally, I use `pygments `and `universal ctags` as plug-in parser in a `python` project.

**Comment by ptrv** [comment]
See here in `YouCompleteMe` [readme](https://github.com/Valloric/YouCompleteMe#the-gycm_collect_identifiers_from_tags_files-option) the only supported format is with `exubarant ctags`.
GNU Global is not supported.

**Comment by moyotar** [comment]
@ptrv Ok. Just now I used command `ctags -e -R --fields+=l` to generate ‘TAGS’ file, and set `ycmd-default-tags-file-name` to `TAGS`. But finally it didn't collect identifiers from `TAGS`.

**Comment by ptrv** [comment]
you shouldn't use the `-e` option. That is not supported for `ycmd`. That's why you can leave the default value of `ycmd-default-tags-file-name`

**Comment by moyotar** [comment]
> d:/WorkSpace//TAGS and d:/WorkSpace/tags are the same file
> Error loading tags-file: (user-error File d:/WorkSpace/TAGS is not a valid tags table)

It seems `tags` file would be turn to `TAGS` automatically

**Comment by moyotar** [comment]
@ptrv Help me solve this.

**Comment by abingham** [comment]
> d:/WorkSpace//TAGS and d:/WorkSpace/tags are the same file
> Error loading tags-file: (user-error File d:/WorkSpace/TAGS is not a valid tags table)

What is reporting this? ycmd, some emacs package, or what?

**Comment by moyotar** [comment]
How to know the package which report this?

**Comment by abingham** [comment]
Where are you seeing it? Is ycmd printing it in the *ycmd-server* buffer?

**Comment by moyotar** [comment]
In `*Messages*` buffer.

**Comment by moyotar** [comment]
@abingham Maybe it doesn't affect `ycmd`. In `*ycmd-server*`, I find nothing about tags file.

**Comment by ptrv** [comment]
I think the problem is related to the case insensitive file system. If you have both files `tags` and `TAGS` Emacs will always find `TAGS` first, even if you have spacified `tags`. I had the same problem on MacOS with case insensitive file system. So either remove `TAGS` or set a different file name for the tags file for ycmd with the option `ycmd-default-tags-file-name`. How exactly you have to create the tags file please look up in the ycmd or youcompleteme project. You cannot use `ctags` with the `-e` option.

**Comment by moyotar** [comment]
I used `ctags -f "mytags" -R --fields=+l` to generate tags file and set `ycmd-default-tags-file-name` to `mytags`. But, it didn't collect any thing from tags file and had nothing output about tags file.
