### ISSUE TITLE
Can't get semantic completion in c++ file.

### ISSUE THREAD

**Issue by moyotar** [abingham/emacs-ycmd#447]
![image](https://user-images.githubusercontent.com/22092607/30894769-58fbe3ea-a378-11e7-96c3-b0e5fbb7dda8.png)

![image](https://user-images.githubusercontent.com/22092607/30894743-2aa4a748-a378-11e7-87aa-f3ab68fd2f39.png)
![image](https://user-images.githubusercontent.com/22092607/30894755-3f5b443a-a378-11e7-8dc9-a717c0fcb02b.png)

**Comment by moyotar** [comment]
I rebuild `ycmd` with option `--clang-completer` and found `llvm 4.0.1` will be downloaded to be used. But I have `llvm.5.0` in my machine instead of `llvm 4.0.1`. Is this the reason?

**Comment by abingham** [comment]
You'll need to ask the ycmd project.

**Comment by moyotar** [comment]
@abingham By the reply from [here](https://github.com/Valloric/ycmd/issues/846), It's said that to update the ycmd dependency would be helpful.

**Comment by ptrv** [comment]
We don't have ycmd as submodule in our repository. So you have to update ycmd.
