### ISSUE TITLE
Tiny modeline suggestion

### ISSUE THREAD

**Issue by quicknir** [abingham/emacs-ycmd#453]
Using spacemacs, most other minor modes have some kind of nice (often unicode) character to represent being on. Ycmd uses, well, "ycmd" which is quite long and so on. It would be nice to allow the user to more easily customize this. I think this can be done by simply doing:

```
 (defun ycmd--mode-line-status-text ()
   "Get text for the mode line."
   (let ((force-semantic
          (when ycmd-force-semantic-completion "/s"))
         (text (pcase ycmd--last-status-change
                 (`parsed "")
                 (`parsing "*")
                 (`unparsed "?")
                 (`stopped "-")
                 (`starting ">")
                 (`errored "!"))))
     (concat ycmd-modeline-symbol force-semantic text)))
```
I.e. the same as the original code, just with `ycmd-modeline-symbol` replacing "ycmd". `ycmd-modeline-symbol` could be a customizable variable that defaults to "ycmd".

**Comment by ptrv** [comment]
See #454

**Comment by quicknir** [comment]
Wow thanks, that was quick! Just a quick question from the pr: I was surprised, but I guess there is probably a reason, to hard code a space before the customisable variable? I haven't had a chance to try this out and see how it will look.

**Comment by abingham** [comment]
I think the intent is so that "ycmd" is distinguishable from other modeline elements. But I think I see your point: with a single-character modeline for ycmd we won't want/need that space.

**Comment by ptrv** [comment]
I think you need the space also in spacemacs with single-character. The macro `spacemacs|diminish` is also always used with the space in the spacemacs config.

**Comment by quicknir** [comment]
Okay cool I had a feeling. I can't test this now, but if there are any
issues I'll open a new issue. Thanks very much!
