### ISSUE TITLE
I was trying to set the server command making use of an environment variable, but its not working.

### ISSUE THREAD

**Issue by justinjk007** [abingham/emacs-ycmd#460]
Instead of hard-cording the location of the install path, I thought I would make an environment variable **YCMD** and then read from it like this

```lisp
  (set 'ycmd-server-command '("python" "-u" (expand-file-name "ycmd" (getenv "YCMD"))))
```

evaluating `(expand-file-name "ycmd" (getenv "YCMD"))` returns `"c:/Program Files/ycmd/ycmd"` so I don;t know why this is not working.

The error I am getting is 
```
File mode specification error: (wrong-type-argument stringp (expand-file-name ycmd (getenv YCMD)))
```

**Comment by abingham** [comment]
Try this:
```
(set 'ycmd-server-command `("python" "-u" ,(expand-file-name "ycmd" (getenv "YCMD"))))
```
Basically, what you're doing right now is putting the list `(expand-file-name "ycmd" (getenv "YCMD"))` inside `ycmd-server-command` without evaluating it. The "backtick quoting" lets you selectively evaluate elements of the list when building it. You can read more about it in [the Emacs documentation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html).

If this works for you, please close this issue. Good luck!

**Comment by justinjk007** [comment]
Yes this worked thank you very much.
I tried this `(set 'ycmd-server-command `("python" "-u" (,expand-file-name "ycmd" (getenv "YCMD"))))` instead of `(set 'ycmd-server-command `("python" "-u" ,(expand-file-name "ycmd" (getenv "YCMD"))))` before which did not work.
