### ISSUE TITLE
two words trigger

### ISSUE THREAD

**Issue by lemon0910** [abingham/emacs-ycmd#475]
In vim, I can set
`let g:ycm_semantic_triggers =  {
                \ 'c,cpp,python,java,go,erlang,perl': ['re!\w{2}'],
                \ 'cs,lua,javascript': ['re!\w{2}'],
                \ }`
two worlds will trigger. for example pr->printf. can emacs-ycmd set?

**Comment by abingham** [comment]
I'm not sure, but I think this is a question for [`company-mode`](https://github.com/company-mode/company-mode). I'm going to close this, but if it turns out to be an issue for `emacs-ycmd`, please re-open it.
