### ISSUE TITLE
Add support for Ivy completion mechanism

### ISSUE THREAD

**Issue by piojanu** [abingham/emacs-ycmd#477]
Hi!

It's just a feature request, I couldn't find anything about it, so I just want to open it as it's really useful thing. When emacs-ycmd receives multiple results from ycmd server it shows it in new window. It would be much much more convenient if it could use tools like [Ivy](https://github.com/abo-abo/swiper) or [Helm](https://github.com/emacs-helm/helm) to list multiple results.

I used both and prefer Ivy (its "lightweight" and fast), so my feature request is for Ivy 😄

**Comment by abingham** [comment]
Are you talking about the `ycmd-display-completions` command? That's not really meant for anything but debugging.

We have a [company completion system](https://github.com/abingham/emacs-ycmd/blob/master/company-ycmd.el) that works really well. Would that meet your needs?

If not, what are you envisioning with ivy? Would the user request completion at a point and be shown the options in ivy? This could be made to work, but I'll admit that it seems less convenient than company.

**Comment by piojanu** [comment]
Nope. I use company-ycmd and its great.
What I mean is e.g. situation when I command emacs-ycmd to find references and I get multiple results  listed in newly created window where I need to hover with cursor exact under list position and then when I hit enter I have it in this new window instead of in the original one where I work. Here is screen shot:

![screen shot 2018-07-17 at 16 36 14](https://user-images.githubusercontent.com/23562932/42824383-0e387a5e-89e0-11e8-9f62-87afe7982b5c.png)

What ivy allows is putting it in scrollable list in mini-buffer like in here (this is example from dump-jump):

![screen shot 2018-07-17 at 16 37 25](https://user-images.githubusercontent.com/23562932/42824469-2cf46e08-89e0-11e8-802b-65efbe6c649f.png)

**Comment by abingham** [comment]
(Sorry for the delay. I'm on vacation and not processing stuff terribly quickly right now.)

Ah, right. This is a good idea. I think where we'd want to look is `ycmd--run-completer-command`. We could pass a `success-handler` that uses ivy. I've had [good experiences with using ivy via `counsel`](https://github.com/abingham/emacs-counsel-codesearch) in the past, and that could probably work here.

Are you up for trying to implement something like this?

**Comment by piojanu** [comment]
Well, I've never written anything in elisp but emacs config and like everyone I think I don't have time 😄 But at the same time, I think it's time to pay back to open source community and I would love to try to do this if you think it isn't that hard and you can tell me where should I start 😉

**Comment by abingham** [comment]
I don't think this will be terribly hard. On a certain level you should be able just pattern-match what you already see in `ycmd-goto-references`. If you follow this thread you'll find yourself in `ycmd-completer` making a call to `ycmd--run-completer-command`. This sends a "completer" command to the server and passes the results to a "success handler". I think you'll want to mimic this stack but pass the results to your own ivy-based handler. I know this is a bit hand-wavy, but this is how I would at least start exploring this work.

You should do this work in a separate `.el` file similar to `company-ycmd.el`, perhaps `ivy-ycmd.el` or `counsel-ycmd.el`. 

By all means let me know if you have questions or want me to test things out as you go. I'm far from an elisp expert, but we'll get it working. Thanks for putting in the effort!

**Comment by piojanu** [comment]
Sory, but I want find time for now. This isn't that critical. You can close this issue for now.

**Comment by abingham** [comment]
I'll keep it open to keep the idea around. It's a good one.

**Comment by abingham** [comment]
@piojanu Try this out: https://github.com/abingham/emacs-ivy-ycmd

**Comment by piojanu** [comment]
Thanks!

Pozdrawiam,
Piotr Januszewski

**Comment by abingham** [comment]
OK, cool. I'll close this out then. If you feel like contributing a bit to `ivy-ycmd` you can send PRs there.
