### ISSUE TITLE
REQUEST [error] Error (error) while connecting to http://127.0.0.1:6259/event_notification

### ISSUE THREAD

**Issue by jiangjiechu** [abingham/emacs-ycmd#480]
Hi there. I'm a win10 newbie user of emacs. 
I installed the ycmd server and it worked on vim properly.
I configured my init.el as follow:
``;;;;;;;;;;;;;;;;;;;;;;;company;;;;;;;;;;;;;;;;;;  ``
``(add-hook 'after-init-hook #'global-company-mode)``
``;;;;;;;;;;;;;;;;;;;;;;;;;;;flycheck;;;;;;;;;;;;;;;;``
``(add-hook 'after-init-hook #'global-flycheck-mode)``
``;;;;;;;;;;;;;;;;;;;;emacs-ycmd;;;;;;;;;;;;;;;;;;;``
``(require 'ycmd)``
``(add-hook 'after-init-hook #'global-ycmd-mode)``
``(set-variable 'ycmd-force-semantic-completion t)``
``(set-variable 'ycmd-server-command (quote ("python" "-u" "c:/Users/peter/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd")))``
``(set-variable 'ycmd-global-config "c:/Users/peter/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py")``
``(require 'company-ycmd)``
``(company-ycmd-setup)``
``(require 'flycheck-ycmd)``
``(flycheck-ycmd-setup)``

I have trouble utilizing emacs-ycmd into my emacs. The client just has trouble connecting the completing server without any useful feedback information.  
``M-x ycmd-show-debug-information`` shows  ::
``Ycmd debug information for buffer init.el in emacs-lisp-mode:``
``No debug info available from server``
``Server is running at: 127.0.0.1:6259``
``Ycmd Mode is enabled``
``--------------------``
``Ycmd version:   1.3snapshot (package: 20180724.1256)``
``Emacs version:  26.0.50``
``System:         x86_64-w64-mingw32``
``Window system:  w32``
And ycmd-server buffer just shows following all the time:
``2018-09-02 16:32:47,384 - DEBUG - No global extra conf, not calling method YcmCorePreload
serving on http://DESKTOP-UMK6THU:6259``
``2018-09-02 16:42:47,565 - DEBUG - Keeping subservers alive``
``2018-09-02 16:52:47,589 - DEBUG - Keeping subservers alive``
``
The most relevant information is:
``REQUEST [error] Error (error) while connecting to http://127.0.0.1:6259/event_notification.``
``REQUEST [error] Error (error) while connecting to http://127.0.0.1:6259/completions. [2 times]``
``REQUEST [error] Error (error) while connecting to http://127.0.0.1:6259/healthy``
``REQUEST [error] Error (error) while connecting to http://127.0.0.1:6259/debug_info``

**Comment by abingham** [comment]
I'm not sure what's going on, and I won't be able to look into it until I'm back from traveling. You might try changing the `request-backend` to see if that changes the behavior.

**Comment by jiangjiechu** [comment]
Thank you very much for attention.
I changed `request-backend` to `(quote url-retrieve)` and everything works alright now.
