### ISSUE TITLE
REQUEST [error] Error (error) while connecting to http://127.0.0.1:54426/event_notification.

### ISSUE THREAD

**Issue by r4nt** [abingham/emacs-ycmd#57]
When ycmd takes a while to get the compile commands (for our internal build system this can take a minute or so) or compile command are not available for some other reason (this can be easily tested with a .ycm-extra-config that does not produce compile commands) I get the error:
REQUEST [error] Error (error) while connecting to http://127.0.0.1:35282/event_notification
instead of a useful error message.

I'm not sure whether that's related to #23 at all (once I wait a while everything works), or whether it's possible to get better responses from emacs-request.

**Comment by naseer** [comment]
I've been getting a similar error (used to work till recently)

REQUEST [error] Error (error) while connecting to http://127.0.0.1:38835/completions.

I'm trying to debug what I changed.

**Comment by naseer** [comment]
Ok, so ycm works in general for me, including for python, but it fails only for C/C++. I'm using spacemacs. I'm not sure where something broke. For the moment, I've given up and I'm using vim for C/C++ where ycmd does work correctly.

**Comment by abingham** [comment]
@naseer Since this issue is closed, would you mind creating a new one with some details about what you're seeing? If you can describe what you're doing, what bad behavior you're seeing, and any relevant-looking data from the `*ycmd-server*` buffer, maybe we can sort things out.

**Comment by naseer** [comment]
Sure, will do that - thanks

**Comment by naseer** [comment]
Thanks for the pointer to the *ycmd-server* buffer - I didn't know about that - it looks like the crash is in ycmd

libclang: crash detected during parsing: {

Should I still open the ticket here or on ycmd ?

**Comment by abingham** [comment]
It can't hurt to open an issue with ycmd. This may be something they know about. With that said, it would probably be nice if emacs-ycmd was a little more helpful when things like this happen. 

If you don't mind, create an issue for emacs-ycmd which includes the contents of the server buffer showing the crash. The point of the issue will be to remind us to make emacs-ycmd give better reporting to the user when this kind of thing occurs. Thanks for your help on this!

**Comment by trishume** [comment]
Also getting the same errors as a Spacemacs user. I'm using the latest `emacs-ycmd` but an old `ycmd` server, which might be the issue.

**Comment by naseer** [comment]
I created https://github.com/Valloric/ycmd/issues/103 on ycmd - but this is something strange - the exact same ycmd version works fine on vim, so something from spacemacs/emacs-ycmd is causing libclang to crash in it.

**Comment by naseer** [comment]
Also @trishume I updated ycmd server to the latest

**Comment by abingham** [comment]
I have trouble imagining what emacs-ycmd could be doing to make libclang barf like that. We just ship some JSON via HTTP to ycmd and wait. 

If you're feeling adventurous, you could run ycmd manually and send messages to it without using emacs-ycmd. The `httprepl` package can help with that. If you want to see what kind of data  we send to ycmd, set `ycmd--log-enabled` to true and look in the `*ycmd-content-log*` buffer.

Actually, if you end up doing that, it might be nice to save the httprepl buffers in the emacs-ycmd source for future debugging and reference...

**Comment by bravomikekilo** [comment]
the bug is quite serious,
the error is triggered on the start 
the complete of C++ is totally break

**Comment by abingham** [comment]
@bravomikekilo This has been a long and involved thread, so I'm not entirely sure what behavior you're talking about. Could you post more details or, even better, open a new issue with details?
