### ISSUE TITLE
Company mode popup gets pushed right.

### ISSUE THREAD

**Issue by trishume** [abingham/emacs-ycmd#64]
In some cases when using company-ycmd, the first character will work great but on typing additional characters the popup will get pushed down and to the right.

For me this only occurs with ycmd, company works fine everywhere else. This happens in both Python and C++ mode and occurs with error buttons disabled and enabled. Not sure about other factors in my config that could cause this, I'll keep looking into it.

Screencast:
http://cl.ly/2s1F1A2r3l08

Screenshot:
![screen shot 2014-11-05 at 9 03 34 pm](https://cloud.githubusercontent.com/assets/887610/4929809/2a8ea2b4-6559-11e4-8e20-a2f01b24bb1e.png)

**Comment by dgutov** [comment]
ensime/ensime-server#754 was a similar bug, caused by the implementation calling the asynchronous callback several times. @abingham, is there a chance that you did/do that, too?

Anyway, hopefully the latest commit in company-mode removes that flaw.

**Comment by trishume** [comment]
@dgutov thanks! I updated to the most recent version of company-mode and emacs-ycmd now works perfectly!
